### ISSUE TITLE
Can't create uberwar

### ISSUE THREAD

**Issue by smahood** [metosin/compojure-api#104]
The command `lein ring uberwar` fails with a newly generated compojure-api project.

`C:\dev>lein new compojure-api my-api`
`C:\dev>cd my-api`
`C:\dev\my-api>lein ring uberwar
Exception in thread "main" java.lang.RuntimeException: No such var: tf/parse-local-date, compiling:(ring/swagger/coerce.clj:16:35)...`

I've got this happening on 2 machines, both running Windows 10 Technical Preview.
One is using `Leiningen 2.5.0 on Java 1.7.0_60 Java HotSpot(TM) 64-Bit Server VM` , the other on `Leiningen 2.5.1 on Java 1.8.0_31 Java HotSpot(TM) 64-Bit Server VM`

**Comment by ikitommi** [comment]
`lein-ring` adds an old version of `clj-time` manually into classpath when doing uberwar. I'll try to do a PR there. Meanwhile, everything should work if you add this to your project dependencies:

```clojure
[clj-time "0.9.0"]
```

**Comment by ikitommi** [comment]
actually, the clj-time seems to be updated in the latest ring. let's wait for a release on that one https://github.com/ring-clojure/ring/commit/95b934aeded980b2a50303ff0585228d5fa11022.

**Comment by ikitommi** [comment]
added clj-time dependency to template. will remove it when new ring is out.
