### ISSUE TITLE
defapi/swagger-docs don't verify that swagger-docs can return successfully

### ISSUE THREAD

**Issue by MichaelBlume** [metosin/compojure-api#106]
In every one of my compojure-api projects I have a unit-test which mocks a request to the /swagger.json endpoint, passes it to the api handler object, and checks for a 200 return code. I've found I need this because sometimes I have a set of schemas which don't quite fit into the swagger spec. My project compiles and starts up, but if I try to load the ui, it crashes with an error fetching swagger.json.

I wonder if it'd be possible to set things up so that in the compilation step for defapi, it checked for the presence of a swagger-docs endpoint, verified that that endpoint returned successfully, and threw an exception if not.

**Comment by ikitommi** [comment]
Hi. I think it's a good idea to verify things at compile-time (as all the data is available). I guess there are options how to implement this:

- at compile-time - could be an extra option to `api` to verify all the models by itself, not 100% proof as part of the swagger-data get's in at runtime (from external middlewares)
- external validator, which takes the `api` and validates it (`api` contains all the route details as it's metadata, implementation details, as an added bonus), would be called from tests (not 100% either)
- your suggestion to automatically poke the swagger-docs endpoint (could optionally also run the real swagger-json validation)

Will think about the best way to implement this.

**Comment by ikitommi** [comment]
Did a small spike what can be done with this. It would be easy to add a compile-time verification of Schema(s) -> JSON Schema conversion, which is the most probable cause of errors anyway.

Verifying automatically the whole swagger-spec would require some extra voodoo (to find out where the spec endpoint is mounted) and would not be 100% complete as there are possible runtime parameters involved.

This works now (in a separate branch):

```clojure
(defrecord IllegalValue [])

(fact "compile-time route verification"
  (fact "is disabled by default"
    (let [api' `(api
                  (GET* "/api/pong" []
                    :return IllegalValue
                    identity))]
      (eval api') => fn?))
  (fact "can be enabled with option"
    (let [api' `(api
                  {:verify-routes true}
                  (GET* "/api/pong" []
                    :return IllegalValue
                    identity))]
      (eval api') => (throws
                       IllegalArgumentException
                       "don't know how to create json-type of: class compojure.api.core_integration_test.IllegalValue"))))
```

, but think I'll toss that away and do:

```clojure
(defapi app ...)

(require '[compojure.api.validator :as v])

(v/verify-models app) ; => nil
(v/validate-spec app) ; (default to "/swagger.json") => nil
(v/validate-spec app "/swagger.json) ; => nil
```

Your thoughts? @Deraen?

**Comment by ikitommi** [comment]
The latest master pushes also the options into the `api` meta, all all data is available for the latter:

```clojure
(require '[compojure.api.sweet :refer :all])
(require '[ring.util.http-status :as status])

(def app
  (api
    {:ring-swagger {:default-response-description-fn status/get-description}}
    (GET* "/user/:id" []
      :name :user
      :path-params [id :- s/Str]
      :return {:id s/Str}
      identity)))

(meta app)
; {:routes {:paths {"/user/:id" {:get {:x-name :user
;                                      :parameters {:path {:id java.lang.String}}
;                                      :responses {200 {:schema {:id java.lang.String}
;                                                       :description ""}}}}}}
;  :lookup {:user {"/user/:id" {:method :get
;                               :params {:id java.lang.String}}}}
;  :options {:ring-swagger {:default-response-description-fn #<core$constantly$fn__4085 clojure.core$constantly$fn__4085@4f9707de>}}}
```

**Comment by ikitommi** [comment]
There is now a `compojure.api.swagger/validator` to validate the apis. 

```clojure
(require '[compojure.api.sweet :refer :all])
(require '[compojure.api.swagger :refer [validate])

(defrecord NonSwaggerRecord [data])

(def app
  (validate
    (api
      (swagger-docs)
      (GET* "/ping" []
        :return NonSwaggerRecord
        (ok (->NonSwaggerRecord "ping"))))))

; clojure.lang.Compiler$CompilerException: java.lang.IllegalArgumentException:
; don't know how to create json-type of: class compojure.api.core_integration_test.NonSwaggerRecord
```

In latest snapshot. One can write own abstractions on top of it, like:

```clojure
(defmacro swagger-api [name & body]
  `(def ~name
     (validate
       (api
         (swagger-ui)
         (swagger-docs)
         ~@body))))

(swagger-api app
  (GET* "/ping" []
    (ok {:ping "pong"})))

(-> {:request-method :get :uri "/ping"} app :body slurp)
; => "{\"ping\":\"pong\"}"

(defrecord Unsupported [])

(swagger-api app
  (GET* "/ping" []
    :return Unsupported
    (ok {:ping "pong"})))
; clojure.lang.Compiler$CompilerException: java.lang.IllegalArgumentException:
; don't know how to create json-type of: class compojure.api.core_integration_test.Unsupported
```

hope this helps.

`validate` could be put also to `sweet`?

**Comment by ikitommi** [comment]
In `0.21.0`.

**Comment by MichaelBlume** [comment]
Nice, thanks! =)
