### ISSUE TITLE
feature: component scoping

### ISSUE THREAD

**Issue by jtmarmon** [metosin/compojure-api#112]
I think it would be really cool if compojure-api could handle passing necessary components to routes.

example syntax:

```clj
(POST* "/my/thing/from/db" []
  :body [d Data]
  :return String
  :components [db sendgrid]
  (db/insert d)
  (sendgrid/email (:email-address d))
  (ok "Thanks!"))
```

**Comment by Deraen** [comment]
You can do this yourself:

```clj
(defn wrap-components
  "Assoc components given in map to the request."
  [handler components]
  (fn [req]
    (handler
      (assoc req ::components components))))

(defn get-components [req]
  (::components req))

(defmethod compojure.api.meta/restructure-param :components
  [_ components acc]
  (update-in acc [:letks] into [components `(get-components ~'+compojure-api-request+)]))
```

Use wrap-components in your system code to associate your components to each request map.

**Comment by jtmarmon** [comment]
wow, thanks for the fast example code :) I realized I could implement it myself, but I figured it might be an interesting idea for a core feature since most people need to deal with this kind of project organization at some point

**Comment by Deraen** [comment]
I guess we could either add this as an example or maybe it could be a separate namespace as it doesn't need to require component namespaces.

**Comment by jtmarmon** [comment]
@Deraen - any idea where I can put this so it's compiled before `lein ring server` boots & tried to call it?  in `app.core` I have my `defapi` and above that line is the definition for `defmethod ... :components` but I'm getting `java.lang.IllegalArgumentException: No method in multimethod 'restructure-param' for dispatch value: :components`.

If I comment out the `:components` on my routes, run `lein ring server`, then uncomment and save (I have `wrap-reload` middleware) it works just fine.

**Comment by Deraen** [comment]
Should be okay as long as the code is required in each namespace where you are using :components restructuring, but I haven't tested with AOT. I would suggest AOT:ing only the main namespace, it prevents loads of issues with the macro magic we are doing.

**Comment by Deraen** [comment]
#114 

I also tested this with AOT (lein aot-uberjar) and it worked.

**Comment by jtmarmon** [comment]
awesome!
