### ISSUE TITLE
quoted full stops - '. - causes an error during macroexpansion of defroutes

### ISSUE THREAD

**Issue by jtmarmon** [metosin/compojure-api#118]
well this is a weird one guys.

try this:
```clj
(defroutes* my-route (GET* "/a" []
                           '.))
```

`CompilerException java.lang.StringIndexOutOfBoundsException: String index out of range: 0`

full stack trace [here](https://gist.githubusercontent.com/jtmarmon/5e6e1fede130a3a3c215/raw/4ae249183c579ffef11098a4edce002f5d6e99e5/gistfile1.txt)

**Comment by ikitommi** [comment]
why are you putting a quoted vector as a body?

**Comment by jtmarmon** [comment]
stumbled upon this trying to collection binding in datomic:

```clj
'[:find ?i
 :in $ [?itemNames ...]
 :where [?i :item/name ?itemNames]]`
```
inputs:
```clj
db, ["car" "cat"]
```

**Comment by jtmarmon** [comment]
that was just the simplest example i could create. i'm actually returning a populated schema as a body, i just narrowed down the issue to this exact cause.

`'a` works
`'.` does not

**Comment by jtmarmon** [comment]
ok this appears to be a backtick issue. macroexapand the above to get:

```clj
(do
  (def
    _my-route
    (with-meta (compojure.core/routes (GET* "/a" [] (quote .)))
               {:source (backtick/syntax-quote ((GET* "/a" [] (quote .)))),
                :inline true}))
  (alter-meta! (var _my-route) assoc :private true)
  (def my-route (var _my-route)))
```

see that backtick line: 
```clj
(backtick/syntax-quote '.)
StringIndexOutOfBoundsException String index out of range: 0  java.lang.String.charAt (String.java:686)
```

i'l take this over there.

**Comment by Deraen** [comment]
This might be good place to start: https://github.com/brandonbloom/backtick/blob/master/src/backtick.clj#L91-L92

it presumes that if symbol has dots, it is namespace qualified symbol.

**Comment by jtmarmon** [comment]
ahhh good tip. thanks a bunch!

**Comment by ikitommi** [comment]
Please poke us when it's fixed, will update the dependency (or you can PR the updated dependency in). 

Hopefully get's fixed.

**Comment by jtmarmon** [comment]
i'll definitely PR ASAP. thanks guys

**Comment by brandonbloom** [comment]
Thanks for the investigation & bug report guys. New version deployed:
https://github.com/brandonbloom/backtick/compare/09574bd4e9b9c9722d68d5e9e01fd5a7ad6be9b5...b927924949a86eb3706dec3f6c224ff79b1de7ae

**Comment by jtmarmon** [comment]
appreciate the quick fix!
