### ISSUE TITLE
Api-level override for coercers

### ISSUE THREAD

**Issue by ikitommi** [metosin/compojure-api#121]
Applying json-coercion for all transports is a bad idea. XML needs extra forwarding-coersion to handle sequence schemas, with Transit we should not do any coercions.

```clojure
(api
   {:options {:coercer-provider-fn my-coercer-provider}}
   (context* "/api" [] ...)
```

`coercer-provider-fn` would be a function `[request, coercion-type] -> coercer-fn`. So, at runtime, we could select the coercer based on any request attributes (transport etc) or we could ignore the whole coercion `(constantly identity)`.

**Comment by ikitommi** [comment]
return values also need coercion and they should be handled separately (400 vs 500 response codes) and response coercion should be made optional (defaulting to true).

**Comment by zamaterian** [comment]
I have a need of decoupling the schema validation from middleware, and do it as a part of the route-fn. 

Response body: 
ex : (PUT "/some/route" [] (my-resource)) ; the response validation happens prior to returning a ring-response to the PUT macro. Currently the impl. I have made is based on a custom 'body-coercer-middleware' thats only arguments the request map with the givens routes swagger-responses and then 
the status the validation happens in my-resource function, based on the status code from the Liberator decision tree. 

Request body: 
I still havn't found any good way of decoupling the validation of the request body. It seems to me that the validation and middleware parsing is very tightly coupled. 

Which makes it very hard to have some middleware that adds the 'body schema' to a request and then 
the my-resource function performs the validation and returns the ring-response map. (eg. malformed? liberator handler, which also performs the parsing of the request body) 

Similary to validation, my-resource function also need to handling the parsing of request according to the content-type and the encoding to a specific format based on the accept header.

If you have any need of any code examples to clarify my intentions, please let me know.

Cheers

**Comment by zamaterian** [comment]
I could imagine that functions is implemented as middleware in restructure function in the compojure-api.meta namespac, a bit like #120 


```Clojure 
; instead of just the swagger responses, all the swagger keys with with schema def's are added to the 
; request for the given route. eg (:responses, :return, :body, :path-params, :query-params) 

(defn setup-coercer-middleware [handler swagger-schemas]
  (fn [request]
    (handler (assoc request :swagger-route-schemas swagger-schemas))))
```

and then there is a middleware-coercer, which is either configuable on a  route or at defapi 
using '{:options {:coercer-provider-fn my-coercer-provider}}'

Evaluation order is 
1) setup-coercer-middleware 
2) middleware-coercer
3) (PUT "/some/route" [] (my-resource))

This enables overriding the coercer/validation by setting a  :coercer-provider-fn (constantly identity)
and then its possible to push the validation into a route implementation (eg. my-resource-fn) 

Cheers :)

**Comment by zamaterian** [comment]
Hi @ikitommi 

I will try to hack something together, that we can discuss :)

**Comment by ikitommi** [comment]
Cool.

Really busy with the real project at the moment, haven't had time to think about this. Have also some ideas for this, will have time on weekend to test it. 

Let's see what we can cook from this :)

**Comment by zamaterian** [comment]
Cool, 
I'm gonna put some more time into this on monday.

This is my first take, still need to extract the schemas for each swagger params and add them to request (extract from lets and letks). 
And move the schema vaildation functions to the default-coercers map. 

Cheers 
Ps: on hyvä viikonloppu


```Clojure
(def default-coercers
  ; todo (constantly should be replaced with each impl schema validation in restructure-param)
  {:responses (constantly identity)
   :query (constantly identity)
   :query-params (constantly identity)
   :body (constantly identity)
   :body-params (constantly identity)
   :headers (constantly identity)
   :header-params (constantly identity)
   :path-params (constantly identity)
   :multipart-params (constantly identity)
   :form-params (constantly identity)})

(defn route-coercer [handler custom-coercers]
  (fn [req]
    (let [req-validators (select-keys  custom-coercers [:body :body-params :query :query-params
                                                       :headers :header-params :path-params
                                                       :multipart-params :form-params])
          res-validators (select-keys custom-coercers [:responses])
         _ (doseq [[k v] req-validator] ; validates request
             (v req (get-in req [:swagger-route-schemas k]))) ; assumes that a validator throws a exception on failure.
         res (handler req)]
         (doseq [[k v] res-validator] ; validates response
             (v res (get-in req [:swagger-route-schemas k]))) ; assumes that a validator throws a exception on failure.
      res)))

(defn setup-coerce-info [handler responses lets letks]
  (fn [request]
    ; reponses and lets and letks should merged into one single map in the same format as default-coerces
    (let [res (handler (assoc-in  (assoc-in  (assoc-in request [:swagger-route-schemas :responses] responses)
                                  [:swagger-route-schemas :lets] lets)
                                 [:swagger-route-schemas :letks] letk ))]
      res)))

(defn restructure [method [path arg & args] & [{:keys [body-wrap]}]]
  (let [body-wrap (or body-wrap 'do)
        method-symbol (symbol (str (-> method meta :ns) "/" (-> method meta :name)))
        [parameters body] (extract-parameters args)
        [lets letks responses middlewares middleware-coerce] [[] [] nil nil default-coercers]
        [lets arg-with-request arg] (destructure-compojure-api-request lets arg)

        ; lets and letks should be changes to a map containing the swagger schemas definitions 
        ; an entry pr. key in default-coerces
        ;
        {:keys [lets
                letks
                responses
                middlewares
                middleware-coerce
                parameters
                body]}
        (reduce
          (fn [acc [k v]]
            (restructure-param k v (update-in acc [:parameters] dissoc k)))
          (map-of lets letks responses middlewares middleware-coerce parameters body)
          parameters)
        body `(~body-wrap ~@body)
        body (if (seq middlewares) `(route-middlewares ~middlewares ~body ~arg) body)
        body (if (seq parameters) `(meta-container ~parameters ~body) body)
        body `(~method-symbol ~path ~arg-with-request ~body)
        body `(route-coercer ~body ~middleware-coerce)
        body `(setup-coerce-info ~body ~responses ~lets ~letks) ; fixme doesnt work yet
        ]
    body))

; todo, havenot yet figured out a good way of merging lets and letks, its
; probably because the origial intent isn't clear to me.
```

**Comment by ikitommi** [comment]
oli hyvä viikonloppu ;)

Gave this a though.

As you noticed, the current coercion is tightly coupled into the generated code. Despite disabling the api-level coercion, let generated `letk`s will still fail for missing keys. Disabling the return body coercion can be done with api-level override (I believe without any modifications to the `restructure` fn).

If you need to bypass both the input schema coercion & `letk` codes (and push the logic into a inner function), I think it could be better not to use the currently shipped metadata handlers from compojure-api.

Do you just need the swagger-docs out of c-api? If so, we could push a new `:swagger` restructuring just for docs. Would consume the (ring-)swagger 2.0 format as-is without any side-effects. Something like:

```clojure
; publishes the data as swagger-parameters without any side-effects / coercion.
; Examples:
; :swagger {:responses {200 {:schema User}
;                       404 {:schema Error
;                            :description "Not Found"} }
;           :paramerers {:query {:q s/Str}
;                        :body NewUser}}}
(defmethod restructure-param :swagger [_ swagger acc]
  (update-in acc [:parameters] deep-merge swagger))
```

You could pass the (accumulated) swagger data into a inner fn via request injection and the inner fns could take care of validation with it. Wrapping the `ANY*` & `:swagger` into a macro would give a nice entry point for all of this, something like:

```clojure
(swagger-endpoint
  {:responses {200 {:schema User}
               404 {:schema Error
                    :description "Not Found"} }
   :paramerers {:query {:q s/Str}
                :body NewUser}}}
  my-resource)
```

hope this helps.

**Comment by zamaterian** [comment]
Hi, 

Thanks for your answer :) 

'api-level override' the return body coercing without touching  the restructure fn ? 


I thing that I can accomplish my need for input coercing by overriden most af the restructure-param !

Not sure whats the correlation between  the keys  are ? 

1)   :query  vs   :query-params
2)    :body vs  :body-params
3)  :headers :header-params 
4)   :path-params  vs ?
 

```Clojure
(defn pre-validation [key value handler]
  (fn [req] (let [req (update-in req [:swagger-coerce key] merge value)
                  res (handler req)]
              res)))


(defmethod compojure.api.meta/restructure-param :path-params [_ path-params {:keys [parameters lets body middlewares] :as acc}]
  (let [schema (compojure.api.meta/fnk-schema path-params)
        ]
    (-> acc
        (update-in [:letks] into [path-params (compojure.api.meta/src-coerce! schema :route-params :query)])
        (assoc-in [:parameters :parameters :path] schema)
        (assoc :body `((pre-validation :path-params ~schema ~@body))))))

(defmethod compojure.api.meta/restructure-param :responses
  [_ responses {:keys [parameters lets body middlewares] :as acc}]
  (let [responses_ (merge (:responses acc) responses)]
  (-> acc
      (update-in [:parameters :responses] merge responses)
      (update-in [:responses] merge responses)
      (assoc :body `((pre-validation :responses ~responses_ ~@body)))
      )))
```

**Comment by zamaterian** [comment]
I figured out a way to disable the body-coercer-middleware fn, by removed the update-in response and and return  restructure-param's 

(defmethod compojure.api.meta/restructure-param :responses
  [_ responses {:keys [parameters lets body middlewares] :as acc}]
  (let [responses_ (merge (:responses acc) responses)]
  (-> acc
      (update-in [:parameters :responses] merge responses)
      #_(update-in [:responses] merge responses)
      (assoc :body `((pre-validation :responses ~responses_ ~@body)))
      )))

**Comment by ikitommi** [comment]
hi,

`:query`, `:body`, etc. are the swagger terms and counterpars to ring request paths `:query-params`, `body-params` etc. So, in Compojure-api we read stuff from request paths and pass the to ring-swagger as swagger-terms.

see: https://github.com/metosin/ring-swagger/blob/master/src/ring/swagger/swagger2_schema.clj

Did an initial version of the api-level overrides, see https://github.com/metosin/compojure-api/commit/f7f6f1b84fb733825f4a30b4723af91554e39d61. Would this be usefull to you? Will finalize and merge on weekend.

cheers,

Tommi

**Comment by ikitommi** [comment]
One can now override the coercion at route-level.

**Comment by zamaterian** [comment]
Thnx, looks good to me :)
