### ISSUE TITLE
HTML doesn't work in route description

### ISSUE THREAD

**Issue by MichaelBlume** [metosin/compojure-api#130]
HTML in the :notes value used to display in the swagger ui but doing the same with the :description key doesn't seem to work.

**Comment by ikitommi** [comment]
Hi. We are passing all data in as-is. All rendering decisions are handled in the swagger-ui. You should write this issue there.

Here are the definitions of the supported formats per field: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md
