### ISSUE TITLE
Disable coercion in 0.21.0?

### ISSUE THREAD

**Issue by grepory** [metosin/compojure-api#131]
Is there a way to disable coercion while specifying a schema type (e.g. for purely documentation purposes)?

I ask, because I'm having some difficulty getting liberator and compojure-api to play well together. I keep getting bizarre and difficult to track down validation errors, like:

```{:errors (not (sequential? a-java.lang.String))}```

I am having a hard time tracking down what, exactly, is happening. So, I'd like to simply disable validation, but keep the return type in the Swagger specification.

**Comment by ikitommi** [comment]
Hi. You can disablw coercion with the latest snapshot. See readme.md for details. Will try to release it this week, should be ~stable. 

See also https://github.com/metosin/compojure-api/issues/121 - might add the `:swagger` as an alternative for documentation only.

**Comment by grepory** [comment]
Outstanding! I was trying to make it work with 0.21, but if you're going to be releasing this week or next, then all is well. Will look forward to the release.

**Comment by ikitommi** [comment]
Released `0.22.0` just for the new pluggable coercion & component-helpers as we are heading for summer vacation.  `0.23.0-SNAPSHOT` now contains all the bleeding edge stuff.
