### ISSUE TITLE
GET* not supporting dot methods

### ISSUE THREAD

**Issue by ghostandthemachine** [metosin/compojure-api#141]
When trying to create a [Slack](https://api.slack.com/methods) style method compojure-api does not support the created routes. They always return a 404. Here is a quick example

```
...
(context* "/brand"
  (GET* ".all" []
    return [Brand]
    (ok (all :brand)))

...
```

**Comment by ikitommi** [comment]
Compojure-api stands on top of Compojure and I believe that's not possible with [it's nested routing](https://github.com/weavejester/compojure/wiki/Nesting-routes) to split uris like that. Please write an issue to Compojure-project of this.

Another option is to use full paths:

```clojure
(GET* "/brand.all" []
  :return [Brand]
  (ok (all :brand)))
```

hope this helps.

**Comment by ghostandthemachine** [comment]
Thanks for the response, this does help. Not as ideal as being able to wrap the method names as contexts but it will do the job.
