### ISSUE TITLE
Error while deploying as an uberwar to a servlet

### ISSUE THREAD

**Issue by mll** [metosin/compojure-api#142]
See here for details:

https://github.com/luminus-framework/luminus/issues/69

This does not happen when the app is run from a jar or lein ring server

Basically, when deployed as a war I get the following error:

java.lang.IllegalArgumentException: No value supplied for key: {:formats (:json-kw :yaml-kw :edn :transit-json :transit-msgpack), :handle-error #<middleware$handle_req_error compojure.api.middleware$handle_req_error@2573e70a>}, compiling:(pythonapi.clj:14:1)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3558)
        at clojure.lang.Compiler$DefExpr.eval(Compiler.java:417)
        at clojure.lang.Compiler.eval(Compiler.java:6708)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.load(RT.java:440)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:1289)
        at voicepin_collector.handler$eval23$loading__4958__auto____24.invoke(handler.clj:1)
        at voicepin_collector.handler$eval23.invoke(handler.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6692)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.load(RT.java:440)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at voicepin_collector.listener$_contextInitialized.invoke(listener.clj:1)
        at voicepin_collector.listener.contextInitialized(Unknown Source)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)

And pythonapi.clj looks like this:

(ns voicepin-collector.routes.pythonapi
  (:require [ring.util.http-response :refer :all]
            [compojure.api.sweet :refer :all]
            [schema.core :as s]
            [voicepin-collector.db.core :as db]
            [clojure.java.io :as io]
            [taoensso.timbre :as logger]
            [ring.swagger.json-schema :as js]
            [bouncer.core :as b]
            [bouncer.validators :as v]
            [voicepin-collector.utils :refer :all]
            ))          

----> Here comes the error, line 14 <----
(defapi pythonapi-routes
   (ring.swagger.ui/swagger-ui "/api/v1/docs" :swagger-docs "/pythonapi.json")
   (swagger-docs "/pythonapi.json" {:info {:title "Voicepin collector"
                         :description "Python API"
                         }})
   (context* "/api/v1/vpusers" []
              :tags ["Users"]
              
   (POST* "/create" []
          :body-params [
                        gid :- Long
                        name :- String
                        sex :- String 
                       ]
          :summary "Creates new user belonging to the given group and returns its object"
          (let [params {:gid gid :name name :sex sex}]
            (let [validation-errors (first (b/validate params 
                                               :gid [v/required v/positive]
                                               :name [v/required [v/min-count 2] [v/max-count 64]]
                                               :sex [v/required [v/matches #"^[MF]$"]]))]
            (if validation-errors (error-response error-code-validation-error validation-errors)
                (let [group (first (db/get-group {:id gid}))]  
                   (if group (if (first (db/get-user-by-name-and-gid {:name name
                                                             :gid gid })) 
                               (error-response error-code-user-exists {"name" "User already exists"})
            (ok (assoc (db/create-user<! {
                                              :gid gid 
                                              :name name 
                                              :sex sex
                                              :uid (get-free-uid)
                                  }) "success" true))) 
            (error-response error-code-no-group {"gid" "No group with this id"})))))))
            
   (POST* "/verify" []
          :body-params [
                         uid :- String
                         gid :- Long
                       ]
          :summary "Verifies if a given user exists"
          (ok {"success" (if (first (db/get-user-by-gid-and-uid {:gid gid :uid uid})) true false)})) 
          
   (POST* "/group/create" []
          :body-params [name :- String]
          :summary "Creates new group with a given name"
          (let [validation-errors (first (b/validate {:name name} :name [v/required [v/min-count 2] [v/max-count 64]]))]
           (if validation-errors (error-response error-code-validation-error validation-errors) 
          (let [group (first (db/get-group-by-name {:name name}))]
          (if group (error-response error-code-group-exists {"name" "Group with this name already exists"})
            (ok (db/create-group<! {:name name})))))))
   
   (GET* "/group/list" []
          :summary "Lists all groups"
          (let [groups (db/get-all-groups)]
          (ok {
               "data" (map (fn [group] [(:id group) (:name group)]) groups)
               "success" true
              })))
   )
   (context* "/api/v1/lrwaves" []
              :tags ["Recordings"]
   
   (POST* "/phrase/create" []
          :body-params [phrase-text :- String
                        gid :- Long]
          :summary "Creates new group with a given name"
          (let [validation-errors (first (b/validate {:phrase-text phrase-text} :phrase-text [v/required [v/min-count 2] [v/max-count 500]]))]
           (if validation-errors (error-response error-code-validation-error validation-errors)
             (let [group (first (db/get-group {:id gid}))]
          (if (not group) (error-response error-code-no-group {"gid" "Group with given id doesn't exists"})
           (ok (db/create-phrase<! {:phrase_text phrase-text :group_id gid})))))))
   
   (GET* "/phrase/list" []
          :query-params [gid :- Long]
          :summary "Lists all phrases in a given group"
          (let [phrases (db/get-phrases-for-group {:group_id gid})]
          (ok {
               "data" (map (fn [phrase] [(:id phrase) (:phrase_text phrase)]) phrases)
               "success" true
              })))
   
   (POST* "/record/list" request 
         :body-params [
                       uid :- String
                       pid :- Long
                      ]
         :summary "Lists all recordings for given user and phrase. phrase = null signals all phrases are taken into account"
         (if-let [user (first (db/get-user-by-uid {:uid uid}))] 
           (ok { "data" (map 
                          (fn [recording] [
                                           (:id recording) 
                                           (full-path-for-file-name 
                                           (:recording_path recording) request) 
                                           (:recording_path recording)
                                           ]) 
                             (filter (fn [recording] (or 
                                                       (= (:phrase_id recording) pid) 
                                                       (< pid 0))) 
                                       (db/get-recordings-for-user {:id (:id user)})
                                      ))
                 "success" true
                 }) (error-response error-code-no-user {"uid" "User does not exist"})))
    
   (POST* "/record/create" []
          :body-params [
                        file :- String
                        session :- Long
                        phrase :- Long
                        user :- String
                       ]
          :summary "Recording upload. file should contain base64 encoded wave"
             (let [user-object  (first (db/get-user-by-uid {:uid user}))
                   phrase-object (first (db/get-phrase {:id phrase}))]
               (if (not user-object) (error-response error-code-no-user {"user" "No such user"})
               (if (not phrase-object) (error-response error-code-no-phrase {"phrase" "No such phrase"})
               (if-let [group (first (db/get-group {:id (:gid user-object)}))]
                 (let [filename (db/save-file-from-base64 file)]
                   (ok (db/create-recording<! {:group_id (:id group)
                                           :user_id (:id user-object)
                                           :phrase_id, (:id phrase-object)
                                           :recording_path filename
                                           :recording_platform "unknown"
                                           :recording_device_id "unknown" 
                                           :microphone_type "unknown"
                                           })))
                 
                 
                 (error-response error-code-no-group {"group" "No group for given user (internal error)"})
               )))))
   ))

**Comment by ikitommi** [comment]
The code sample has some issues with brackets. What version of compojure-api are you using? Could you try `lein new compojure-api tst` and see if that works ok.

**Comment by mll** [comment]
Ok, this is not compojure-api bug, this is (or actually was...) a Luminus bug. For anyone having such a problem please refer to https://github.com/luminus-framework/luminus/issues/69
