### ISSUE TITLE
Coercion issues with non-Schema objects

### ISSUE THREAD

**Issue by lightsaber** [metosin/compojure-api#144]
First off, I am a Java programmer trying to learn Clojure so I apologize if the answer to this should be obvious.

I am having issues getting a MongoDb response that validates as a User that looks like this:
```Clojure
(s/defschema User {:_id org.bson.types.ObjectId :user_id String :first_name String :last_name String})
```

It appears to be having issues though when I try to return it in a route even though the schema validates:
```Clojure
(defapi app
  (swagger-ui)
  (swagger-docs
    {:info {:title "UserManager"
            :description "Compojure Api example"}
     :tags [{:name "hello", :description "Say hello, get a user"}]})
  (context* "/hello" []
    :tags ["hello"]
    (GET* "/user/:id" [id]
      :return (s/maybe User)
      :body [userData (s/maybe (d/find "testusername" ))]
      :summary "say hello"
      (ok userData))))
```

Log says this doesn't work:
```
INFO: Opened connection [connectionId{localValue:930, serverValue:248}] to 192.168.59.104:27017
java.lang.IllegalArgumentException: No implementation of method: :walker of protocol: #'schema.core/Schema found for class: org.bson.types.ObjectId
at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
at schema.core$eval6790$fn__6802$G__6781__6807.invoke(core.clj:105)
at schema.coerce$eval8706$coercer__8707$fn__8708$fn__8709.invoke(coerce.clj:31)
at schema.utils$memoize_id$fn__6517.invoke(utils.clj:49)
at schema.core.MapEntry.walker(core.clj:666)
at schema.coerce$eval8706$coercer__8707$fn__8708$fn__8709.invoke(coerce.clj:31)
at schema.utils$memoize_id$fn__6517.invoke(utils.clj:49)
at schema.core$map_walker$iter__7368__7372$fn__7373.invoke(core.clj:727)
at clojure.lang.LazySeq.sval(LazySeq.java:40)
at clojure.lang.LazySeq.seq(LazySeq.java:49)
at clojure.lang.RT.seq(RT.java:484)
at clojure.core$seq.invoke(core.clj:133)
at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30)
at clojure.core.protocols$fn__6078.invoke(protocols.clj:54)
at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
at clojure.core$reduce.invoke(core.clj:6289)
at clojure.core$into.invoke(core.clj:6341)
at schema.core$map_walker.invoke(core.clj:725)
```

I was assuming that Schema just doesn't understand how to use the ObjectId object but it validates:
```Clojure
(s/validate User (mc/find-one-as-map db "users" { :user_id "testusername" })))
```

Is there a custom coercion that I need to create to do this?  I'm new to the language and the frameworks so I'm not really familiar enough with the language in the documentation to know where I'm supposed to go from there.

**Comment by ikitommi** [comment]
The `:body` should be used if the route accepts a schema as a body, eg. when sending JSON/Transit/Yaml to the route. Your route is a `GET*`, so I guess you are not expecting any body from the client.

so I guess you want to say:

```clojure
(GET* "/user/:id" [id]
  :return (s/maybe User)
  :summary "say hello"
  (ok (d/find "testusername")))
````

or with typed path-params:

```clojure
(GET* "/user/:id" []
  :return (s/maybe User)
  :path-params [id :- s/Int]
  :summary "say hello"
  (ok (d/find "testusername")))
```

if you expect a client to send User then the body should be used like this:

```clojure
(POST* "/user" []
  :return (s/maybe User)
  :body [user User]
  :summary "echoes a user"
  (ok user))
```

hope this helps.

**Comment by lightsaber** [comment]
Ok, so I made the suggested changes and Swagger complains:

```
Caused by: java.lang.IllegalArgumentException: don't know how to create json-type of: class org.bson.types.ObjectId
```

So I assume there is some type of hint or something I have to do to help it understand what to do with that object.

**Comment by ikitommi** [comment]
Compojure-api uses ring-swagger to convert the Schema definitions into Swagger JSON Schemas. Unfortunately, `ObjectId` is not supported [out-of-the-box](https://github.com/metosin/ring-swagger#out-of-the-box-supported-schema-elements), so you have two choices:

1) convert the `ObjectId` into Strings manually (and describe the schema field as `s/Str`)

2) add swagger-support to it yourself, see https://github.com/metosin/ring-swagger#schema-to-swagger-json-schema-transformation. Same applies to JSON serialization, by default Cheshire doesn't know how to serializa `ObjectId`s. If you are using Monger, it has a `monger.json` ns you can import.

with monger, this should work:

```clojure
(ns mng.handler
  (:require [compojure.api.sweet :refer :all]
            [ring.util.http-response :refer :all]
            monger.json)
  (:import  [org.bson.types ObjectId]))

;; adding swagger-support for ObjectId
(require '[ring.swagger.json-schema :as json-schema])
(defmethod json-schema/json-type ObjectId [_] {:type "string"})

(defapi app
  (swagger-ui)
  (swagger-docs)
  (context* "/hello" []
    (GET* "/" []
      :return {:id ObjectId}
      (ok {:id (ObjectId.)}))))
```

show find someone with time to write good tutorial.

**Comment by lightsaber** [comment]
Wow, that is really nice.  Fixed my problem, thanks!

**Comment by ikitommi** [comment]
no prob.
