### ISSUE TITLE
Treat authentication as a first class citizen

### ISSUE THREAD

**Issue by nikos** [metosin/compojure-api#145]
It would be fantastic if dealing with authentication would be possible right out of the box (my guess is #122 is going into that direction?).

I tried the access token example from the compojure README to hook in via restructure-param (unfortunately modifying code will break reloading with ring server), and I guess more people these days would love to see how to protect the modifying aspects of their API.

**Comment by Deraen** [comment]
Not directly related to the problem, but do you have example of reloading breaking? We are usually using Component workflow with reloaded.repl but I don't see why ring reload wouldn't work.

**Comment by nikos** [comment]
To separate things, I created a new issue over at #147

**Comment by ikitommi** [comment]
Would love to see this. I'll change the #122 to contain the security in general.
