### ISSUE TITLE
swagger2.0 not support on chrome?

### ISSUE THREAD

**Issue by zjhmale** [metosin/compojure-api#149]
i just create a sample app use

```
lein new compojure-api xxx
```

and when i start server i can see nothing in chrome and in chrome console there is some error

![2015-08-11 6 18 20](https://cloud.githubusercontent.com/assets/6234553/9195509/f0878134-4055-11e5-8571-a0201eacb8eb.png)

but it works fine with safari and firefox and when i checkout swagger1 it works fine with chrome

and for now

compojure-api v0.22.0 or above don't support chrome
compojure-api v0.13.1 do support chrome

how can i fix with it?

**Comment by Deraen** [comment]
Works fine for me. Chrome 46.

**Comment by ikitommi** [comment]
and here with Version 44.0.2403.130 (64-bit).

try updating the ui manually to latest with `[metosin/ring-swagger-ui "2.1.1"]` and see if that helps. If not, please raise issue to https://github.com/swagger-api/swagger-ui.

**Comment by zjhmale** [comment]
i'm also with 44.0.2403.130 (64-bit) and it's the latest version on osx 10.9
i will try to manually update ring-swagger-ui

**Comment by zjhmale** [comment]
i tried

![2015-08-11 6 55 33](https://cloud.githubusercontent.com/assets/6234553/9196098/9a7f62d4-405a-11e5-948d-6de5a14d4a70.png)

and still not work on chrome for me...

**Comment by ikitommi** [comment]
please try the official swagger-ui 2.1.1 from the repo I linked. If that doesn't work either, the issue is beyond our reach, might be a rogue chrome plugin.

**Comment by zjhmale** [comment]
ok i will try thx:)

**Comment by zjhmale** [comment]
swagger-ui 2.1.1 just works fine with chrome... so what's the real problem..

**Comment by ikitommi** [comment]
ring-swagger-ui has few small js-changes so that it's easy to embed from the apps. Problem is that we aren't seeing this error with Chrome so can't help. You could:

1. compare the vanilla swagger-ui & ring-swagger-ui and try to figure why it's not working with you.
2. package the vanilla swagger-ui manually and use that

**Comment by zjhmale** [comment]
ok i will try that or maybe i can just use firefox or safari to see the swagger doc thx a lot :)
