### ISSUE TITLE
how can i add description for params

### ISSUE THREAD

**Issue by zjhmale** [metosin/compojure-api#151]
i want to add descriptions for `query-params` `body-params` and `path-params` how can i do that i just add `:description xxx` after param and got an error

**Comment by zjhmale** [comment]
![2015-08-13 12 04 43](https://cloud.githubusercontent.com/assets/6234553/9242429/85cc04c8-41b3-11e5-8d08-cc03d8fbdea0.png)

and the desciption will show in the swagger doc for each parameter

**Comment by ikitommi** [comment]
see https://github.com/metosin/compojure-api#more-about-models & https://github.com/metosin/compojure-api/blob/master/examples/src/examples/thingie.clj#L60-L61

**Comment by zjhmale** [comment]
thx :) i should read the docs more patiently

**Comment by zjhmale** [comment]
if i have a param with default value and i want to add description for it is it the right way below?

```clojure
(POST* "/minus" []
      :return      Total
      :body-params [x :- (describe Long "first param")
                    {y :- (describe Long "second param") 3}]
      :summary     "x-y with body-parameters."
      (ok {:total (- x y)}))
```

**Comment by ikitommi** [comment]
looks right.

**Comment by zjhmale** [comment]
cool!! thx a lot :)
