### ISSUE TITLE
java.lang.RuntimeException: Method code too large!

### ISSUE THREAD

**Issue by zjhmale** [metosin/compojure-api#153]
after i add swagger support for my api service from compojure to compojure-api when i run

```
lein jar
```

it comes out the runtime exception

```
java.lang.RuntimeException: Method code too large!, compiling:(core.clj:1:1)
```

how can i fix it ?  i split my routes into small ones but still get the runtime exception

**Comment by zjhmale** [comment]
i just put ```(handler/site (-> app-routes middlewares))``` into ```defapi``` function but there is no swagger doc this way so i also put the routes functions in app-routes in ```defapi``` too and that's the reason that make the ```defapi``` method to large and the real issue is that why can not put a ring handler in ```defapi``` function and show swagger doc

**Comment by Deraen** [comment]
Check this https://github.com/metosin/compojure-api/issues/135

If this is the same problem, we should probably mention this in readme.

**Comment by zjhmale** [comment]
so what exactly should a do should a use ```lein ring uberjar``` or aot the core namespace?

**Comment by Deraen** [comment]
Are you currently using AOT? It can cause problems and it can be fixed by only AOT compiling the main namespace. Example: https://github.com/metosin/compojure-api/issues/129#issuecomment-114505102

**Comment by zjhmale** [comment]
no i just have 

```
;; :aot []
```
in my ```project.clj``` file

i will try just aot the main namespace

**Comment by zjhmale** [comment]
after add

```
:aot [core namespace]
```

in ```project.clj``` still get the exception

**Comment by zjhmale** [comment]
i fix it through [#129 comment](https://github.com/metosin/compojure-api/issues/129#issuecomment-114505102) @Deraen  best thx!!!
maybe you should put this issue on readme i think this is a common issue when some one has a lot of routes when use compojure-api

**Comment by zjhmale** [comment]
such a black magic in AOT! i should spend some time to figure out what is really going on here do you have some reference links or blogs to read? @Deraen @ikitommi

**Comment by ikitommi** [comment]
no links, sorry. Ping us too if you find a good reference :)
