### ISSUE TITLE
optional body-params

### ISSUE THREAD

**Issue by zjhmale** [metosin/compojure-api#154]
i have a api

```clojure
(POST* "/signout" []
      :body-params [{device_token :- (describe String "device token") ""}]
      :summary "xxx"
      body)
```

and the `device_token` is already a optional key but when i post this api with no json object it will occur `#schema.utils.ErrorContainer{:error (not (map? nil))` so i have to post an empty json object such like `{}` as the body params to avoid this error but it is quite not so easy for me to change all the frontend code to post an empty json object when there is no `device_token` how can i fix this issue?

should i change the source code in `ring.swagger.schema` namespace? because i found this function makes this issue come out

```clojure
(defn coerce!
  "Coerces a value against a schema using a given coerser. If no errors,
   returns the coerced value, otherwise throws a schema.utils.ErrorContainer
   enriched with :type ::validation.

   Optional third parameter is a dispatch value to ring.swagger.coerce/coercer,
   defaults to :json"
  ([schema value] (coerce! schema value :json))
  ([schema value type]
    (let [result (coerce schema value type)]
      (if (error? result)
        (throw+ (assoc result :type ::validation))
        result))))
```

**Comment by ikitommi** [comment]
There is no coercion from nil -> map, so the coercion fails. You have at least the following options:

1. override the default coercion, see https://github.com/metosin/compojure-api#coercion by adding the nil->map coercion to `:body` & `:response`.

2. use `:body` restructuring, which allows you to describe the whole body form. really noicy with defaults, but works:

````clojure
(POST* "/signout" []
  :body [{:keys [device_token] :or {device_token ""}} (s/maybe {(s/optional-key :device_token) (describe String "device token")})]
  :summary "xxx"
  body)

3. write your own restructuring `:opt-body-params`, which would work just like `:body-params` but would wrap it in `s/maybe` behind the scenes.

hope this helps.
```

**Comment by zjhmale** [comment]
ok i get it this part  `{:keys [device_token] :or {device_token ""}` just deconstruct the params and this part `(s/maybe {(s/optional-key :device_token) (describe String "device token")})` just to show that there maybe a map there

but i just modify [some source code](https://github.com/zjhmale/ring-swagger/blob/jihui_dev/src/ring/swagger/schema.clj#L55) in ring-swagger and reclojar my own ring-swagger and compojure-api to fix the issue

**Comment by ikitommi** [comment]
That disables the coercion (including validation) for all apis. But will close this as there are multiple solutions to this.

**Comment by zjhmale** [comment]
could you show the right way to do this as you said there are multiple solutions to fix this

**Comment by ikitommi** [comment]
I would go with 1, there are links to tests giving examples on this on the README.

```bash
lein new compojure-api nilmaps
cd nilmaps
vi src/nilmaps/handler.clj
lein ring server
```
handler.clj:
```clojure
(ns nilmaps.handler
  (:require [compojure.api.sweet :refer :all]
            [ring.util.http-response :refer :all]
            [compojure.api.middleware :as mw]))

(defn nil-to-map-matcher [schema]
  (if (and (map? schema) (not (record? schema)))
    (fn [x]
      (if (nil? x) {} x))))

(defn my-coercion [_]
  (update-in mw/default-coercion-matchers [:body] (partial some-fn nil-to-map-matcher)))

(defapi app
  {:coercion my-coercion}
  (swagger-ui)
  (swagger-docs)
  (POST* "/signout" []
    :body-params [{device_token :- (describe String "device token") ""}]
    :summary "xxx"
    (ok {:token device_token})))
```

testing:
```bash
➜  nilmaps  http post :3000/signout device_token=123
HTTP/1.1 200 OK
Content-Length: 15
Content-Type: application/json; charset=utf-8
Date: Wed, 26 Aug 2015 05:15:52 GMT
Server: Jetty(7.6.13.v20130916)

{
    "token": "123"
}

➜  nilmaps  http post :3000/signout
HTTP/1.1 200 OK
Content-Length: 12
Content-Type: application/json; charset=utf-8
Date: Wed, 26 Aug 2015 05:15:16 GMT
Server: Jetty(7.6.13.v20130916)

{
    "token": ""
}
```

**Comment by zjhmale** [comment]
thx:) i should read README more carefully
