### ISSUE TITLE
no-AOT docs & samples

### ISSUE THREAD

**Issue by ikitommi** [metosin/compojure-api#155]
- write to README how to handle AOT.
- update examples so that they don't AOT too eagerly
- see https://github.com/metosin/compojure-api/issues/153, https://github.com/metosin/compojure-api/issues/135 & https://github.com/metosin/compojure-api/issues/129#issuecomment-114505102

**Comment by zjhmale** [comment]
but currently the example path is just a whole project if i want add an example project to show how to use aot where should i put it

**Comment by ikitommi** [comment]
consumed by #329
