### ISSUE TITLE
File-upload binding is fixed to 'file'

### ISSUE THREAD

**Issue by freakinruben** [metosin/compojure-api#157]
Hi,

I have a file-upload route in my API and it seems that the name of the binding for my upload is fixed:

So, this works:

```clojure
(POST* "/upload" []
  :multipart-params [file :- upload/TempFileUpload]
  :middlewares [upload/wrap-multipart-params]
  (log/info file)
  (ok))
```

But when I change 'file' to something else, my '/upload' route doesn't even get called:

```clojure
(POST* "/upload" []
  :multipart-params [test-name :- upload/TempFileUpload]
  :middlewares [upload/wrap-multipart-params]
  (log/info test-name)
  (ok))
```

Is this expected behaviour or am I doing something wrong here maybe?

Thanks,
Ruben

**Comment by Deraen** [comment]
It should work.

**Comment by Deraen** [comment]
I tested this and I couldn't reproduce the problem. Please reopen with more details if you still have problems.
