### ISSUE TITLE
how can i customize Request URL

### ISSUE THREAD

**Issue by zjhmale** [metosin/compojure-api#162]
after i launch the project and get the swagger doc correctly and i click the `Try it out!` button in one of the apis and get the `Response Messages` include `Request URL` `Response Body` `Response Code` and `Response Headers` like the pic show below

![2015-08-31 6 57 49](https://cloud.githubusercontent.com/assets/6234553/9577526/31f43c3e-5014-11e5-853e-47607f2e2aca.png)

but i just did some trick in nginx so the `Request URL` is just generate from the clojure code but not the real api url for other engineers expect to see so how can i customize it like 

```clojure
(POST* "/minus" []
      :return      Total
      :body-params [x :- (describe Long "first param")
                    {y :- (describe Long "second param") 3}]
      :summary     "x-y with body-parameters."
      :request-url   "the real Request URL i want someone else to see"
      (ok {:total (- x y)}))
```

does compojure-api support this? i just read the whole doc and examples and some source code of compojure-api and ring-swagger but can not come out an idea to fix this

**Comment by Deraen** [comment]
Sounds similar to servlet context: https://github.com/metosin/ring-swagger/blob/master/src/ring/swagger/core.clj#L139-L155

Do I understand correctly that you are proxying certain urls to Clojure app? I.e. `/clj/minus` from nginx to `/minus` at Clojure app?

I think `X-Forwarded-Context` header is somewhat standard way to pass this info from proxy server to the app. We could read that from request in ring-swagger and we could build correct urls.

Until then, as a workaround you could wrap your all routes in `context*` similar to that of the proxy context.

**Comment by zjhmale** [comment]
um.. i did some url rewrite in nginx 

if i have this route in clojure app

```clojure
(POST* "/foo/:name/bar" []
      :path-params [(name :- (describe String "the name")]
      ;; i want this feature
      :request-url   (str "http://" name ".mydomain.com/bar")
      (ok {:total (- x y)}))
```

and i did the url rewrite in nginx 

```nginx
server {
    listen       80;
    server_name  *.mydomain.com;
    
    if ( $host ~* (\b(?!www\b)[\w-]+)\.mydomain.com) {
        set $name $1;
    }

    location /api/ {
        rewrite ^/api/(.*)$ /foo/$name/$1 break;
        proxy_pass http://clojureapp/;
    }
}
```

so android ios app or web frontend will use `http://${name}.mydomain.com/api/bar` to interact with the clojure app.

 but in the swagger doc this api url will be `http://xxx.mydomain.com/foo/${name}/bar` just like it defined in the clojure code.

 so how could i change `http://xxx.mydomain.com/foo/${name}/bar` to `http://${name}.mydomain.com/api/bar` in the `Request URL` part.

i think inject a `request-url` param in `POST*` is a good idea to do this. and i don't think `X-Forwarded-Context` can fit this need

i wish i make my issue clear in this comment, could you provide some solutions?

**Comment by Deraen** [comment]
`http://${name}.mydomain.com/api/bar` wouldn't work with Swagger and I don't think we can support this special case.

Rewriting subdomain name to path-parameter doesn't seem like a good idea to me.
You could think about passing the subdomain to clojure app as a HTTP header instead.

My advice would be to structure Clojure app urls so that they are the same in nginx and clojure app.

**Comment by zjhmale** [comment]
thx for the reply:) maybe you are right, but to reconstruct the clojure app's route is a huge work so thx all the same. maybe i will take your advice if i got enough time.
