### ISSUE TITLE
DELETE* can not pass body params in swagger ui

### ISSUE THREAD

**Issue by zjhmale** [metosin/compojure-api#163]
i currently have an api 

```clojure
(DELETE* "/deletesomething" []
      :body-params [name :- (describe String "the name of it")]
      :summary "a delete api"
      xxx))
```

but after i interact with the api use swagger doc it just come out the exception

```
Expected a map at key-path [], got type null
```

and i read the source code to find where this exception occurs

* [letk-input-schema-and-body-form](https://github.com/Prismatic/plumbing/blob/master/src/plumbing/fnk/impl.clj#L138)

* [fnk-schema](https://github.com/metosin/compojure-api/blob/master/src/compojure/api/meta.clj#L52)

* [where exception occurs](https://github.com/metosin/compojure-api/blob/master/src/compojure/api/meta.clj#L221)

so i add a debug middleware to see what is going on

```clojure
(defn wrap-debug [dt]
  (fn [req]
    (do
      (if (not (nil? req))
        (println req)))
    (dt req)))
```

and i found there is nothing in the `:params` or `:body-params` in ring request.

but when i interact with this api use `post-man` it works fine.

and there is nothing wrong with `POST*` `PUT*` etc.

so the problem is that the swagger doc generate by `compojure-api` can not pass the `:body-param` to the clojure app with `DELETE*`. but it can pass `path-params` or `header-params`.

so is this a `ring-swagger` or `ring-swagger-ui` bug?

**Comment by zjhmale** [comment]
cat anyone fix this? @ikitommi @Deraen

**Comment by zjhmale** [comment]
just `body-params`, `path-params` works fine.

**Comment by ikitommi** [comment]
this is an swagger-ui issue, see https://github.com/swagger-api/swagger-ui/issues/1435

**Comment by zjhmale** [comment]
ok i see they just fix it in swagger-js, so currently we can do nothing to fix this issue?

**Comment by zjhmale** [comment]
it seems that if i replace the content-type param of the input request before it get into `wrap-param` middleware can simply fix this, maybe there is a better way
