### ISSUE TITLE
Support for schema 1.0.0

### ISSUE THREAD

**Issue by ludwinas** [metosin/compojure-api#165]
Currently your library depends on schema 0.4.4. As far as I can tell, compojure-api breaks when I add `[prismatic/schema "1.0.0"]` as a direct dependency.

Of course I can get by with using the version that compojure-api depends on, but it'd be nice to be eventually able to leverage the new schema features.

**Comment by ikitommi** [comment]
see https://github.com/metosin/ring-swagger/issues/62, contributions also welcome!

**Comment by Deraen** [comment]
I have pushed a snapshot.

**Comment by ikitommi** [comment]
and it's finally out `0.24.0`!
