### ISSUE TITLE
Nulls in schema for arrays when build with uberjars

### ISSUE THREAD

**Issue by dzhus** [metosin/compojure-api#169]
Sometimes compojure-api yields "null" in Swagger schema, rendering the whole schema invalid:

```json
  "basePath": "/",
  "definitions": {
    "Body11477": {
      "type": "object",
      "properties": {
        "articles": {
          "description": "Article IDs",
          "type": "array",
          "items": null
        }
      },
      "required": [
        "articles"
      ]
    },
```
The offender here is `articles` field in `Body11477`.
Here's the corresponding Clojure code for the route:
```clojure
            (POST* "/topic/:topic-id/population" []
                   :summary "Add content to a topic"
                   :body [body {:articles (describe [Article] "Article IDs")}]
                   :path-params
                   [topic-id :-
                    (describe Topic "ID of a topic to add content to")]
                   (ok (populate-topic topic-id (:articles body))))
```

The same code produces working schema for `articles` **when using `lein ring server`**:

```
"articles":{"description":"Article IDs","type":"array","items":{"type":"integer","format":"int64"}}
```

Any ideas?

**Comment by dzhus** [comment]
Looks like there're more differences between schemas produced with uberjar and ring server: https://gist.github.com/dzhus/d430638836bd4e2bd757

**Comment by dzhus** [comment]
Oh yes, in a clean directory it doesn't work with lein ring server at once as well - I have to add and delete a whitespace in my main class file, then it starts producing working schema.

Does this have something to do with :aot?

**Comment by Deraen** [comment]
Probably caused by aot.

Check this: https://github.com/metosin/compojure-api/issues/155

**Comment by dzhus** [comment]
I have a single-file project and `:aot [tb.main]` in my project definition and in `uberjar` profile.

**Comment by dzhus** [comment]
I removed all mentions of :aot and :main from uberjar profile and project top-level map and switched to building with `lein ring uberjar` and this fixed it
