### ISSUE TITLE
Support merging swagger-docs :paths key

### ISSUE THREAD

**Issue by emidln** [metosin/compojure-api#170]
It would be handy if you could expose additional paths that are provided elsewhere in the stack to swagger. Something like this:

```clj
(swagger-docs {:paths {"/metrics" {:get {:summary "App and JVM Metrics"}}}})
```

that merged the paths calculated via api/defapi with the provided paths.

**Comment by ikitommi** [comment]
might work if we just change the `merge` to `deep-merge` in here: https://gist.github.com/Deraen/ef7f65d7ec26f048e2bb#file-handler-clj-L20. Want to do a PR?

**Comment by ikitommi** [comment]
Should be fixed now. see https://github.com/metosin/compojure-api/blob/ec093778a5052ec664e2a14eec64a5cee40b6d80/test/compojure/api/integration_test.clj#L1219-L1232. Also supports extra paths via runtime request injection (from middewares). Deployd in `0.24.1-SNAPSHOT`.

**Comment by ikitommi** [comment]
`0.24.1`.

**Comment by emidln** [comment]
Thanks!
