### ISSUE TITLE
Type mismatch when using Liberator resources

### ISSUE THREAD

**Issue by johnboy14** [metosin/compojure-api#175]
When attempting to use the :return keyword in my GET* function, I get a strange response error

```
{
  "errors": "(not (sequential? a-java.lang.String))"
}
```

When I remove the :return keyword I don't get the error above.  I assume the function that handles the schema validation is only expecting a body.  Does anyone else use Liberator in conjunction with the swagger-docs function?. 

```
(context* "/search" []
            :tags ["search"]

            (GET* "/" []
                  :return [UserProfile]
                  :query-params [term :- s/Str]
                  :summary "returns ok"
                  search-term))
```

Profile schema

```
(defschema UserProfile {:email Str
                        :img_url Str})
```
Liberator Resource.  search-for-term returns a vector of maps.
```
(defresource search-term
             :authorized? true
             :allowed-methods [:get]
             :available-media-types ["application/json"]
             :handle-ok (fn [ctx]
                          (search-for-term (get-in ctx [:request :params :term]))))
```

**Comment by ikitommi** [comment]
hi. 

I believe Liberator does the json-encoding and by so, the search-terms returns a JSON String and thus the schema-check for `[UserProfile]` fails.

It would work if you could disable the json-encoding from your resource somehow. Not a Liberator expert, so don't know how to do that, sorry. 

Compojure-api uses [ring-middleware-format](https://github.com/ngrunwald/ring-middleware-format) for request & response formatting, done in the middleware chain, transparently outside of the handler. This enables the handlers to return raw clojure data (wrapped into ring-responses), data get's serialized into whatever the client requested. So this anyway should work:

```clj
(require '[ring.util.http-response :refer [ok]])

(context* "/search" []
  :tags ["search"]

  (GET* "/" []
    :return [UserProfile]
    :query-params [term :- s/Str]
    :summary "returns ok"
    (ok (search-for-term term))))
```

hopefully this helps.

**Comment by ikitommi** [comment]
I think we can't do more here. Please poke the Liberator guys and reopen if we can help with something.
