### ISSUE TITLE
Undocumented routes when importing from different source file.

### ISSUE THREAD

**Issue by rcanepa** [metosin/compojure-api#182]
I am trying to organice my routes in separated files by their type/task (contacts, users, items, etc.) and then importing all of them in one main file in which I have configured the swagger documentation. However, all routes that have been imported from other files aren't being considered by swagger.

This is a extract of my main route table (swagger configuration belongs here):

````
(defn api-endpoint [{users-db :users-db contacts-db :contacts-db :as config}]
  (api
   (ring.swagger.ui/swagger-ui
    "/swagger-ui")
   (swagger-docs
    {:info {:title "SimpleClerk API"
            :description "SimpleClerk's CRM API"
            :tags [{:name "users" :description "Application's users."}
                   {:name "contacts"}
                   {:name "contacts_v2"}]}})

   (context* "/api/v1" []
             :tags ["api"]

             (context* "/users" []
                       :tags ["users"]

                       (GET* "/" []
                             :return [UserSchema]
                             :summary "Return the list of users."
                             (ok (fetch-users users-db)))

                       ;; ...
                       (DELETE* "/:id" []
                                :return s/Int
                                :path-params [id :- s/Uuid]
                                :summary "Delete the user with a given id."
                                (ok (delete-user! users-db id))))

             (context* "/contacts" []
                       :tags ["contacts"]
                       ;; importing contacts routes
                       (contacts-endpoint contacts-db)
                       ;; adding a dummy route for testing purposes
                       (GET* "/foo" []
                             :return s/Int
                             :summary "Dummy route"
                             (ok 1))

                       )

             )))
````
 
And my contacts routes files looks like this:
````
(defn contacts-endpoint [db]
  (defroutes* contacts-route []
    (GET* "/" []
          :return [Contact]
          :summary "Return the list of contacts."
          (ok (fetch-contacts db)))

    (POST* "/" []
           :return s/Uuid
           :body [contact Contact]
           :summary "Create a contact record."
           (ok (create-contact! db contact)))

    ))
````

You can see here that my configuration only shows me the dummy route and not the ones that I imported from the other file.
<img width="1005" alt="swaggerss" src="https://cloud.githubusercontent.com/assets/3418513/11692263/72eee916-9e7d-11e5-95bf-8fb28f22e13c.png">

I am sure that those external routes are working because I can request them without problems. Any idea of what could be wrong in my configuration?

**Comment by ikitommi** [comment]
hi.

currently you can't do that. The swagger-docs (and reverse-route lookup-table) are generated at compile-time, not at runtime. So, currently, to get the swagger-docs out from extra routes, you need to define the extra routes as a Var, defined by `defroutes*`. See [examples](https://github.com/metosin/compojure-api/blob/master/examples/src/examples/ordered.clj). 

This is not good and a source of confusion, so the plan is to move all swagger-resolution from compile-time to run-time. Also gives other benefits like better support for Liberator & snappier dev-flow. Plan is to get this out before the end of the year. Before that, you should use `defroutes*` and [pass the Dependencies to routes at runtime](https://github.com/metosin/compojure-api#passing-components-via-request).

hope this helps.

**Comment by ikitommi** [comment]
see https://github.com/metosin/compojure-api/issues/178

**Comment by rcanepa** [comment]
Hi! 

Good to know that this feature is in compojure-api's roadmap! Meanwhile, I will group my routes in one file because I want to keep my endpoint as system components. The defroutes* macro without a function enclosing it to inject dependencies is not compatible with what I want.

Thanks for your quick answer!

**Comment by ikitommi** [comment]
Working on this via https://github.com/metosin/compojure-api/issues/178#issuecomment-168911544.

**Comment by ikitommi** [comment]
this works on internal 1.0.0-SNAPSHOT.

**Comment by ikitommi** [comment]
Merged in master. We will try to finalize 1.0.0 this/next week. See [Changelog](https://github.com/metosin/compojure-api/blob/master/CHANGELOG.md#100-snapshot) for details.
