### ISSUE TITLE
Error on using created HTTP response function from ring-http-response.

### ISSUE THREAD

**Issue by rcanepa** [metosin/compojure-api#184]
Hi, testing the http response functions in my compojure-api based API, I found a problem when I use the created http response as a wrapper of my handler. In short, I wanted to return a 201 status code after creating a record instead of a 200. So, I changed the response function from ok to created just as you can see here:

```clojure
 (POST* "/" []
               :return s/Uuid
               :body [user UserSchema]
               :summary "Create a user record."
               (created (create-user! users-db user)))
```

An for some reason, I am getting an error (500 status code) with the next message:

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /api/v1/users. Reason:
<pre>    Unrecognized body: 82f298d4-8f39-4de6-9a45-7cb4252d074b</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>

I can confirm that this endpoint works fine if I use the ok response function.
</html>

**Comment by Deraen** [comment]
Try:

```
:responses {201 {:schema s/Uuid}}
```

**Comment by Deraen** [comment]
Ring-middleware-format will only encode response bodies which are either collections or if response has `:compojure.api.meta/serializable?` set to truthy value. The serializable value is set by body-coercer-middleware which checks if the response schema is specified for response status. In this case there is no schema specified for status 201 so no serializable flag is set. And Uuid is not a collection, so ring-middleware-format doesn't encode it.

**Comment by rcanepa** [comment]
Oh, I understand. Thanks for the explanation.
Problem solved!

**Comment by Deraen** [comment]
Also, if you are using JSON, I would encourage you to wrap the Uuid in a map. AFAIK some browsers can have problems with raw values as JSON "root object". Not sure if this holds for Transit or other formats.

**Comment by rcanepa** [comment]
Ok, I will do that too. Thanks for the advice @Deraen !

**Comment by ikitommi** [comment]
if you don't want to fiddle with the actual status code (numbers), you can also:

```clj
(require '[ring.util.http-status :as status])

 (POST* "/" []
   :responses {status/created {:schema s/Uuid}}
   :body [user UserSchema]
   :summary "Create a user record."
   (created (create-user! users-db user)))
```
