### ISSUE TITLE
Specifying the :headers keyword in :responses

### ISSUE THREAD

**Issue by rahulmutt** [metosin/compojure-api#189]
I've tried vectors, maps, and plains strings for the values of the :headers keyword inside of the value of the status code in the map of :responses and I'm getting "unexpected exceptions" regardless of what I try. Basically, I want to document that I'm returning a header from one of my API calls.

**Comment by Deraen** [comment]
Hmm, never tried this but I guess it should work as `:responses` is passed nearly as is to Swagger. Could you provide some example code?

**Comment by rahulmutt** [comment]
I resolved this by searching through the ring-swagger repo. [Here](https://github.com/metosin/ring-swagger/blob/4ecd1ffb228cc9459a9b436300fdc09663feb268/test/ring/swagger/swagger2_test.clj#L112) is an example of a test that uses it.

When using the :headers keyword, the format should be a map of keywords whose names are the header names and the values are the schema that should be validated against the concrete values.

I'll update the wiki showing an example of this - the wiki mentioned it which is why I wanted to try in the first place.

**Comment by Deraen** [comment]
Thanks!
