### ISSUE TITLE
Clean way to handle OPTIONS calls

### ISSUE THREAD

**Issue by rahulmutt** [metosin/compojure-api#193]
I have to deal with CORS in the API I'm building and I am required to send OPTIONS calls corresponding to every API call. For every API call, there is a requirement that a certain header (say x-authorization) is required. This can be cleanly done by wrapping all the api calls in a context which has like so
```clojure
(context* "" []
    :header-params [x-authorization]
    ...)
```
Now the problem comes when I add the OPTIONS calls. I'm placing these OPTIONS calls outside of this context and somehow the header requirement is being forced on those calls as well. And since the browser sends the OPTIONS call on the frontend, I have no control over what it sends. The API is expecting x-authorization to be present, but it will not be present in the OPTIONS call.

Now the quick and dirty solution is to use :header-params for every API call. Is there a cleaner way to do it with compojure-api? Why is it that the requirement is forced even though I am placing it outside of the context? I assumed the route matcher matches from top to bottom, matching the first pattern, processing it, and stopping there.

**Comment by Deraen** [comment]
> I assumed the route matcher matches from top to bottom, matching the first pattern, processing it, and stopping there.

Yeah, that's how it should work. And to be clear, "top to bottom" means code. Is your OPTIONS route before the context in code? Example with more code could be helpful.

**Comment by mtkp** [comment]
@rahulmutt do you need to do any special handling of the OPTIONS calls? If not, consider adding some cors middleware that handles those calls before they even get to your `(context* ...` forms. I've previously used https://github.com/r0man/ring-cors to build a solution.

**Comment by rahulmutt** [comment]
I made the headers required again and it's working. I think I made a mistake when first made the options calls and now it's corrected.

@mtkp, thanks for the suggestion! I took a look at it and it looks like it a bit more lenient than I would like.
