### ISSUE TITLE
Breaking changes in 1.0.0 release

### ISSUE THREAD

**Issue by Deraen** [metosin/compojure-api#194]
- `*` postfix will be removed from all names
- `defapi` will be removed
- `swagger-ui` and `swagger-docs` handlers/routes will be removed
    - instead will be built as options into `api`
- `compojure.api.sweet` namespace will be removed
    - instead `compojure.api.core` will contain most or all of the useful stuff?
    - This would allow us to remove dependency on potemkin.

**Comment by ikitommi** [comment]
if `sweet` would be removed, need to reorganize code (`path-for`, `describe` etc.). Ring-swagger depends on Potemkin, so would not really remove (transitive) dependencies.
