### ISSUE TITLE
path parameter conflicting with dot extensions like ".json"

### ISSUE THREAD

**Issue by taeold** [metosin/compojure-api#196]
Some of our service endpoints needs to accept a path parameter followed by an optional `.json` extension, e.g.

```
http://foo.com/api/id-12345.json
```

Currently compojure-api cannot create routes like this without introducing some oddities, e.g.

```clojure
user=> (defapi app
         (GET* "/api/:id.json" []
           :path-params [id :- String]
           (ok {:message (str "Hello " id)})))

user=> (meta app)
{:routes [["/:foo/:id.json" 
 {:get {:parameters 
  {:path 
   {:id.json java.lang.String,  ;; uh-oh
    :id java.lang.String}}}}]],
 :lookup {}, :options {}}
```

In the above example, we intended to have a path parameter `:id` followed by `.json` extension, but compojure-api creates a path parameter `:id.json` instead.

What if we change the behavior of compojure-api to match against `.` when parsing out path parameters?    This would disallow having `.` in path parameters, but clojure vars does not allow `.` anyway. Thoughts?

**Comment by taeold** [comment]
related: metosin/ring-swagger#82

**Comment by ikitommi** [comment]
How does vanilla Compojure handle this?

**Comment by taeold** [comment]
If I understand correctly, compojure uses [clout](https://github.com/weavejester/clout) to handle route matching (e.g. https://github.com/taeold/compojure/blob/master/src/compojure/core.clj#L40).

Clout can handle the aforementioned use cases.

```clojure
user=> (require '[clout.core :as clout])
nil
user=> (clout/route-matches "/:id.json" {:request-method :get :uri "/123.json"})
{:id "123"}
```
