### ISSUE TITLE
HTTP body parsing doesn't work with multiple defapi route definitions

### ISSUE THREAD

**Issue by empperi** [metosin/compojure-api#206]
When application has multiple defapi definitions all meta handlers regarding HTTP body breaks in later defapi handlers (eg. :body and :body-params or custom meta handlers).

This happens since HTTP body is a mutable InputStream object which can be read only once. Within a single defapi definition body byte array data is read and inserted into request as ByteArrayInputStream so that later body reading will still get the original byte array data.

However after this part it's done again for the second defapi declaration but now the original HTTP body is already consumed and no body can be read. This issue comes effectively from the fact that defapi declares a bunch of middlewares itself thus causing multiple middleware identical middleware declarations for the application for different route contexts.

**Comment by Deraen** [comment]
You might be able to disable the offending ring-middleware-format ("r-m-f") middleware by setting `:format :formats` to an empty vector. This way `wrap-restful-params` should be no-op and it won't read body. You will then need to provide your own r-m-f middleware.

Another workaround would be to use the same byte-array / ByteArrayInputStream workaround as r-m-f uses, before calling either api. This way apis would get separate input streams. (This approach is not very efficient, but neither is r-m-f.)

**Comment by ikitommi** [comment]
Not much we can do, mutable is evil. But instead of saying:

```clj
(routes
  (api 
    (context "/a" []
      (GET "/ping" [] (ok {:ping "a"}))))
  (api 
    (context "/b" []
      (GET "/ping" [] (ok {:ping "b"})))))
````
one should say:

```clj
(api
  (context "/a" []
    (GET "/ping" [] (ok {:ping "a"})))
  (context "/b" []
    (GET "/ping" [] (ok {:ping "b"}))))
````

this way, there is only one mw consuming the IS on the pipeline. hope this helps.

**Comment by manuel-uberti** [comment]
Sorry to comment on a closed issue, but what if I need to wrap two (or more) `defapi` with distinct middlewares. For instance:

```
(compojure/defroutes first-routes
  (-> first-defapi
      (compojure/wrap-routes auth/wrap-auth-api)
      (compojure/wrap-routes auth/wrap-auth-token)
      (compojure/wrap-routes restful/wrap-restful-format)))

(compojure/defroutes second-routes
  (-> second-defapi
      (compojure/wrap-routes restful/wrap-restful-format)))

(compojure/defroutes app
  (-> (compojure/routes
       (route/resources "/")
       first-routes
       second-routes)
      cookies/wrap-cookies
      reload/wrap-reload))
```

In this case, the body in second-routes is always nil.

**Comment by NickYadance** [comment]
I had this problem too and it's exactly as @manuel-uberti  described. My solution is to do as @ikitommi tells. Though all the api defined in a single file looks not clean but it's OKAY.
