### ISSUE TITLE
Array of string in schema

### ISSUE THREAD

**Issue by jeremieca** [metosin/compojure-api#209]
Hello,

How do you describe an array of string in schema ?

    (def CampaignDebug
        {:id s/Str
         :name s/Str
         :tags [s/Str]                  ; Failed { "s/Str": "missing-required-key" }
    })

**Comment by SeriousBug** [comment]
That is the correct way actually. Trying to validate it does work:

```clojure
(require '[schema.core :as s])

(s/validate
            {:id s/Str
             :name s/Str
             :tags [s/Str]}

            {:id "123"
             :name "ABC"
             :tags ["a" "b" "c"]})
```

The error suggests that there is a missing key. Is this the actual schema you are using? If yes, can you look at the data you are validating against this to make sure it has all the required keys?

**Comment by jeremieca** [comment]
Thanks ! The problem was not here...

I wrote `:path-params [id s/Str]` instead of `:path-params [id :- s/Str]`
