### ISSUE TITLE
:query-param destructuring

### ISSUE THREAD

**Issue by joshwils82** [metosin/compojure-api#221]
I am reIatively new to clojure development so please forgive me if this is a basic question, but is it possible to destructure the query params into a map that can have schema validation applied to it?

Something along the lines of

:query-params [& point :- s/Point]

or

:query-params {:x x, :y y} -: s/Point

Idea being that I dont have to manually constuct  a map from a subset of the query-params, similar to how the body mapping works.

**Comment by ikitommi** [comment]
Hi,

`:query-params` uses the [defnk syntax](https://github.com/plumatic/plumbing#bring-on-defnk), while the `:query` uses a normal let, so normal clojure destructuring can be applied there:

```clj
:query [{:keys [x y]} s/Point]
```

If you want to allow any extra keys (like the `:query-params` does), you can make the Schema loose :

```clj
:query [{:keys [x y]} (assoc s/Point s/Keyword s/Any]
```

This way, the clients can pass `?x=10&y=20&whatever=false` and it still works.

Hopefully this helps.

**Comment by ikitommi** [comment]
btw, the source code for all of those is here: https://github.com/metosin/compojure-api/blob/master/src/compojure/api/meta.clj#L110-L264.

**Comment by joshwils82** [comment]
Thanks, that was the exact information I need.  I really appreciate it!
