### ISSUE TITLE
content-type of response seems to be overridden

### ISSUE THREAD

**Issue by mootboy** [metosin/compojure-api#222]
When generating a response it seems like the content-type is overridden (by coercion?) when using compojure-api 1.0.0-RC2. Example response:

`{:status 200, :headers {"content-type" "application/jwk-set+json"}, :body {:keys [{:kid "i kid"}]}}`

curl to the resource returns the following:

```
< HTTP/1.1 200 OK
< Date: Wed, 17 Feb 2016 11:19:11 GMT
< Content-Length: 26
< Content-Type: application/json; charset=utf-8
* Server Jetty(7.6.13.v20130916) is not blacklisted
< Server: Jetty(7.6.13.v20130916)
<
* Connection #0 to host localhost left intact
{"keys":[{"kid":"i kid"}]}
```
Here's the resource definition in full:

```
(GET "/" []
     :summary "Return the available public keys as a JSON Web Key Set"
     :return JWKSet
     :produces ["application/jwk-set+json"]
     :responses {200 {:description (status/get-description 200)}
                 401 {:description (status/get-description 401)}
                 403 {:description (status/get-description 403)}}
     (conj (r/response {:keys [{:kid "i kid"}]})
           {:headers {"content-type" "application/jwk-set+json"}}))
```

**Comment by Deraen** [comment]
Ring-middle-format always sets the content-type when encoding the body: https://github.com/ngrunwald/ring-middleware-format/blob/master/src/ring/middleware/format_response.clj#L202

To work around this you could encode the body yourself: `(cheshire.core/generate-string ...)`

This is something that should probably be eventually be fixed in ring-middleware-format (or possible successor).

**Comment by mootboy** [comment]
Thank you @Deraen, I guess that makes sense from the perspective of the middleware.

I think there may be two issues in that case (have to admit I have not dug very deep though):

1. From the documentation for function you linked it sounds like it's supposed to adhere to the negotiated content-type from the `Accept` header. Adding the correct `Accept: application/jwk-set+json` to the request still result in a response with `Content-Type: application/json` however.
2. Return content-types are not limited to the content-types listed in the `:produces` parameter in the resource configuration.

Would you agree or am I missing something?

**Comment by mootboy** [comment]
OK, I've dug a bit deeper and see how to do this now. Closing.
