### ISSUE TITLE
broken on Google App Engine

### ISSUE THREAD

**Issue by mobileink** [metosin/compojure-api#227]
FYI the latest version uses https://github.com/fge/msg-simple which uses threads in a way that is disallowed on GAE.  I don't have time to adapt the code to use appengine's ThreadManager, but the offending line in the stacktrace, in case you're interested, is

 com.github.fge.msgsimple.provider.LoadingMessageSourceProvider$1.newThread(LoadingMessageSourceProvider.java:91)

**Comment by ikitommi** [comment]
Thanks. We could lazily require the FGE (only when needed) to support this.

**Comment by mobileink** [comment]
Not a pressing issue for me at the moment but it would be nice to have compojure-api on gae again.  it worked just fine previously.

**Comment by Deraen** [comment]
The problem dependency: `metosin/ring-swagger -> metosin/scjsv -> com.github.fge/json-schema-validator -> com.github.fge/json-schema-core -> com.github.fge/uri-template -> com.github.fge/msg-simple`

**Comment by ikitommi** [comment]
Should work now with the following:

 ```clj
[metosin/compojure-api "1.0.3-SNAPSHOT" :exclusions [[metosin/scjsv]]]
```

You can't call `compojure.api.swagger/validate` on your apis on GAE as it lazily tries to load the FGE and it's excluded. But, that's intended for testing anyways.

**Comment by ikitommi** [comment]
Added a short wiki-page about GAE, feel free to fix and add (any relevant) information the page: 

https://github.com/metosin/compojure-api/wiki/Google-app-engine
