### ISSUE TITLE
dots in params fail spectacularly

### ISSUE THREAD

**Issue by shriphani** [metosin/compojure-api#229]
Hi,

I tried defining a `GET` endpoint which requires periods like so:

```clojure
(GET "/plus" []
        :return {:result Long}
        :query-params [x.foo :- Long, y :- Long]
        :summary "adds two numbers together"
        (ok {:result (+ x.foo y)}))
```

And it fails with this error:

https://gist.github.com/shriphani/f01993cece0830b4bf0d1ceba894cc4c

The period in the endpoint is not up to me to decide - it is a 3rd-party thing. I managed to get it to work by using the request object directly so it isn't a really huge issue for me but would be nice to discover these pitfalls early.

Regards,
Shriphani

**Comment by ikitommi** [comment]
Hi.

That is a language feature - sadly Clojure doesn't seem to support dots in destructuring keys:

```clj
(plumbing.core/letk [a.b {:a.b 1}] a.b)
; clojure.lang.Compiler$CompilerException: java.lang.ClassFormatError: Illegal field name "a.b" in class boot/user$eval57812, compiling:(/var/folders/39/j64jmzc96xdd40ghbvw72rk80000gn/T/boot.user1044241209419011549.clj:1:1)
;             java.lang.ClassFormatError: Illegal field name "a.b" in class boot/user$eval57812

(let [{:keys [x.foo]} {:x.foo 1}] x.foo)
; clojure.lang.Compiler$CompilerException: java.lang.ClassFormatError: Illegal field name "x.foo" in class boot/user$eval58039, compiling:(/var/folders/39/j64jmzc96xdd40ghbvw72rk80000gn/T/boot.user1044241209419011549.clj:1:1)
;             java.lang.ClassFormatError: Illegal field name "x.foo" in class boot/user$eval58039
```

As a workaround, you can use resources, which are fully data-driven:

```clj
(resource
  {:get {:parameters {:query-params {:x.foo Long, :y Long, s/Keyword s/Any}}
         :responses {200 {:schema {:result Long}}}
         :handler (fn [request]
                    (ok {:result (+ (-> request :query-params :x.foo)
                                    (-> request :query-params :y))}))}})
```

hope this helps.

**Comment by shriphani** [comment]
@ikitommi I actually passed in the request directly but this would be nice to place in `README.md`. If you want, I can send you a PR.

**Comment by Deraen** [comment]
`:query` restructuring should allow this also:

```clj
(GET "/plus" []
  :return {:result Long}
  :query-params [query {:x.foo Long, :y Long}]
  :summary "adds two numbers together"
  (ok {:result (+ (:x.foo query) (:y query))}))

**Comment by shriphani** [comment]
@Deraen that looks nice as well. But I think it is important one of these be present in the project README.

**Comment by Deraen** [comment]
I added note on the end of this section: https://github.com/metosin/compojure-api/wiki/Building-Documented-Apis#query-path-header-and-body-parameters

Readme is kept very simple on purpose and doesn't mention corner cases.

**Comment by ikitommi** [comment]
Would love to get better docs for compojure-api as a community/user effort!

The page @Deraen edited, is the old README. It's bloated and could be split into smaller pages, one per specific topic. One page could be dedicated how to write endpoints - walking through all available the meta-data handlers with examples. I like the concise format of the [Liberator docs](http://clojure-liberator.github.io/liberator/doc/resource-definition.html).

Would you we interested in (re-)writing that part?

**Comment by shriphani** [comment]
Sure. I don't mind - is the endpoints section documented somewhere?

**Comment by ikitommi** [comment]
Yes, the old README is the place.

**Comment by ikitommi** [comment]
I think the original problem is resolved. For the docs, feel free to ask any questions, here or in Slack (#ring-swagger).

cheers.
