### ISSUE TITLE
Cannot inject request headers spec into generated swagger.json

### ISSUE THREAD

**Issue by trieloff** [metosin/compojure-api#232]
I’m trying to get this:
```
"responses": {
          "200": {
            "description": "My default response",
            "headers": {
              "Content-Type": {
                "type": "String"
              }
            }
          }
```
When I add `{:responses {200 {:schema s/Any :description "My default response" :foobar {"Content-Type" {:type "String"}}}` I get:
```
       "responses": {
          "200": {
            "description": "My default response",
            "foobar": {
              "Content-Type": {
                "type": "String"
              }
            }
          }
```
 
So adding `foobar` does work. However when I change it to `{:responses {200 {:schema s/Any :description "My default response" :headers {"Content-Type" {:type "String"}}}` I’m getting:
```
        "responses": {
          "200": {
            "description": "My default response"
          },
```
So the `headers` parameter gets filtered out.

The same is true when using `:headers {"Content-type" String}` – essentially anything in the `:headers` map will get ignored or overwritten.

**Comment by ikitommi** [comment]
Should be fixed in `[metosin/compojure-api "1.1.2"]`.  See https://github.com/metosin/ring-swagger/commit/b93f7433f6c2f7f914633490bf68a6934eab2d54 & https://github.com/metosin/compojure-api/commit/4cfc2ea8bebe65bf4207ad5ff4e7109d88aa032f for details.
