### ISSUE TITLE
Poor test documentation

### ISSUE THREAD

**Issue by dvbeato** [metosin/compojure-api#233]
Poor tests documentation in how to tests endpoints.
I have an post endpoint that works fine, but if i tried create test, I'm getting an error and have no documentation/wiki to help me showing how to test a post endpoint.

**schema**
```clojure
(s/defschema Invite
  {:inviter s/Int
   :invited s/Int})
```

**test**
```clojure
(testing "expected POST request to /invitations returns the new invite"
    (let [response (app (-> (mock/request :post "/api/invitations" {:inviter 1 :invited 2})))
          body     (parse-body (:body response))]
      (is (= (:status response) 200))
      (is (= body {:inviter 1 :invited 2}))))
``` 

**error**
lein test :only invite-rewards-api.handler-test/api-test

FAIL in (api-test) (handler_test.clj:22)
expected POST request to /invitations returns the new invite
expected: (= (:status response) 200)
  actual: (not (= 400 200))

lein test :only invite-rewards-api.handler-test/api-test

FAIL in (api-test) (handler_test.clj:23)
expected POST request to /invitations returns the new invite
expected: (= body {:inviter 1, :invited 2})
  actual: (not (= {:errors "(not (map? nil))"} {:inviter 1, :invited 2}))

**Comment by Deraen** [comment]
The `ring.mock.request/request` third parameter is not for setting body params but URL query params. You need to use `ring.mock.request/body` instead: https://ring-clojure.github.io/ring-mock/ring.mock.request.html

**Comment by ikitommi** [comment]
Added a placeholder in wiki for writing api tests. Would you like to contribute to that?

https://github.com/metosin/compojure-api/wiki

**Comment by dvbeato** [comment]
Thanks @Deraen , worked well.

```clojure
(testing "expected POST request to /invitations returns the new invite"
    (let [response (app (->
                          (mock/request :post "/api/invitations")
                          (mock/content-type "application/json")
                          (mock/body  (json/write-str {:inviter 1 :invited 2 }))))]
      (is (= (:status response) 200))))
```

Great @ikitommi , of course I will contribute. 😃

**Comment by ikitommi** [comment]
Big thanks for contributing!
