### ISSUE TITLE
Support the clojure.spec as an alternative to primatic/schema

### ISSUE THREAD

**Issue by rukor** [metosin/compojure-api#234]

**Comment by ikitommi** [comment]
Hi, sure. Have to study the `core.spec` first. Ideas and PRs welcome.

**Comment by ikitommi** [comment]
Related: https://github.com/metosin/ring-swagger/issues/95

**Comment by ikitommi** [comment]
Related progress:
- [Spec-tools](https://github.com/metosin/spec-tools)
- [Spec-swagger](https://github.com/metosin/spec-swagger)

Spec is still in alpha and the current implementation that the libs lean on is subject to change. If you want to contribute, please check the repos and the remaining issues in there.

alpha support planned for 1.2

**Comment by ikitommi** [comment]
will be part of 2.0.0, plan to ship it within a month.

**Comment by ikitommi** [comment]
alpha5 has now swagger-support, via spec-tools. There is a small example repo to play with: https://github.com/metosin/c2

**Comment by ikitommi** [comment]
Done! :)
