### ISSUE TITLE
Correct way to set custom Content-Type for responses?

### ISSUE THREAD

**Issue by bard** [metosin/compojure-api#236]
I'd like to set a custom `Content-Type` for responses, to be able eventually to use something like `application/vnd.foobar.v0+json`. 

I tried this:

```clojure
(def app
  (api
   {:swagger
    {:ui "/api-docs"
     :spec "/swagger.json"
     :data {:info {:title "Sample API"}}}}

   (GET "/test" []
        :produces "text/plain"
        (ok "Hello, world!\n"))))
```

But the Content-Type header just disappears:

```
$ curl -D-  http://localhost:3000/test
HTTP/1.1 200 OK
Date: Thu, 30 Jun 2016 10:42:20 GMT
Content-Length: 14
Server: Jetty(7.6.13.v20130916)

Hello, world!
```

After seeing #235 I tried to set `:format` to `{:formats []}`, but it made no different. Not sure how #108 plays into this.

https://github.com/metosin/compojure-api/wiki/Swagger-integration says:

> By default, the application wire-format serialization capabilities (:produces and :consumes) are injected in automatically by the api machinery.

But doesn't mention how to depart from the default.

I'm using compojure-api 1.1.3.

Is this supported?

**Comment by ikitommi** [comment]
Hi. Currently, you can do this by creating a custom formatter for the `ring-middleware-format` that compojure-api is using. See https://github.com/ngrunwald/ring-middleware-format for details how to write one. I guess it would work just like the `:json-kw` but with different contenty-type. You can install your formatter to compojure-api like this:

```clj
(api
  {:format {:formats [my-custom-json-formatter :edn ....]}}
   ...)
```

hope this helps. Should be much easier in future, about to rewrite r-m-f (async + faster).

**Comment by ikitommi** [comment]
with `1.1.6`, this should be easier. Added test for this.

**Comment by ikitommi** [comment]
But the root-cause is here: https://github.com/ngrunwald/ring-middleware-format/issues/53. Before that is fixed, you could add a middleware outside of the `api`, which reads the `:content-type` header and resets that.

**Comment by ikitommi** [comment]
closing this now. https://github.com/metosin/muuntaja will replace r-m-f soon.
