### ISSUE TITLE
Ability to set :return, :body etc on the fly

### ISSUE THREAD

**Issue by miloandmilk** [metosin/compojure-api#237]
HI there, 

I am looking at allowing schema's to be altered at runtime through a UI config. I am unable to see any documentation on how to rebind :return or :body at run time or use a function as their value. It would be good if a function could also be passed in to a route to be bound to :return and :body so the latest model could be retrieved/generated on the fly.

If the functionality exists -or if there is a way to make it work, can someone please point me to it, otherwise could this be implemented? I am happy to have a look if someone can point me to the relevant code where 1) the swagger.js is created and 2: where the schema validates the incoming request and outgoing response. I am very new to compojure-apid do not know the source.

Thanks in advance.

**Comment by ikitommi** [comment]
I would try `resource` for this, see https://github.com/metosin/compojure-api/wiki/Resources-and-Liberator. Resources are fully data-driven, easier to compose than normal route macros. You can catch request (or any request-params coerced) at `context` and generate a resource out of that - at run-time. Something like:

```clj
(context "/path" request
  (resource
    {:post {:parameters {:body-parameters (body-for request)}
            :responses {200 {:schema (return-for request)}}}}
            :handler (fn [coerced-request] ...)})))
```

not near computer, so didn't test that. Might work ;)

the swagger-stuff in in `compojure.api.swagger`, if you want to read the source. Coercion-related things in `compojure.api.coercion`.

**Comment by miloandmilk** [comment]
Hi ikitommi,

Thanks for the pointers. I have now tried resources and thy are really good for defining routes at runtime (which is something we need) however I can't seem to find a way to update the attributes after the routes have been defined.

Feel free to close this and I will dig around further to see how I can achieve this. I'll keep you posted.

**Comment by ikitommi** [comment]
I can also check this when at computer later this week.

**Comment by ikitommi** [comment]
Did an example on defining runtime-resources from different schemas:

https://github.com/metosin/compojure-api/tree/master/examples/reusable-resources

hope this helps.

**Comment by miloandmilk** [comment]
Hi ikitommi,

Sorry for the delay in coming back to you on this. This looks to be exactly what I need.

Thank you for your time in putting the guide together - it has been a big help.

Kind regards,
Sean
