### ISSUE TITLE
Options to be less intrusive on the non-swagger routes

### ISSUE THREAD

**Issue by amalloy** [metosin/compojure-api#240]
I am using `compojure-api` to provide documentation for an existing API server, and it does a great job at producing those docs. However, as my API server is performance sensitive, It currently has very few middlewares wrapped around it, and also a few middlewares that are faster but less flexible versions of the standard middlewares - for example, a version of `wrap-params` that doesn't support passing the same parameter twice.

But as far as I can tell, using the `(api ...)` macro automatically includes several rather expensive middlewares (via `api-middleware`), wrapped around all of my handlers, whether I need them or not. I would like an option to get the wonderful swagger-ui routes added to my existing routes, without making any other substantive changes to those routes. In particular, I would really like to avoid including stuff like coercing the input according to the schema I use for documentation, and checking my API''s return values for spec conformance.

Is there some way to do this built in already that I'm missing?

**Comment by ikitommi** [comment]
Hi. `api` is indeed rather heavy/opinionated, intended to replace the original `compojure.handler/api` and thus contains the same `wrap-params` etc. If there are ill versions of middlewares or missing options, would love to get a PR.

I copy-pasted a guide "just for docs" from the old README/wiki [i-just-want-the-swagger-docs-without-coercion](https://github.com/metosin/compojure-api/wiki/Building-Documented-Apis#i-just-want-the-swagger-docs-without-coercion) to a [better place in wiki](https://github.com/metosin/compojure-api/wiki/Swagger-integration#i-just-want-the-swagger-docs-without-coercion).

For perf, you could also disable extra (or all) `ring-middleware-format` formats too:

```clj
(api
  {:swagger ...
   ; disable all schema coercion
   :coercion (constantly nil)
   ; remove extra ring-middleware-format negotiation, can be [] too.
   :format {:formats [:json-kw]}}
   ...)
```

We are about to rewrite `ring-middleware-format` for better perf and to support upcoming async ring & interceptors.

hope this helps.

**Comment by amalloy** [comment]
What I'd love is a way to opt out of being wrapped with `api-middleware` entirely, since I already have all the middlewares I need. Additionally, some way to specify parameters in a place that doesn't cause them to actually be extracted from the request would be nice. The server I inherited is written in a style like:

    (defn handle-help [{{:keys [x y z]} :query-params :as request}]
      (...))

    (def handler (GET "/help" [] handle-help))

ie, not making use of compojure's request-destructuring feature, and keeping the implementation separate from the routing logic. But in order to get compojure-api to document the parameters `x/y/z`, I need to put them in the definition of the `GET`, which means that the `GET` macroexpands into a `letk` that extracts all this stuff I don't need from the request, only to throw it all away. That is, if I write my `GET` like so

    (GET  "/help" []
      :query-params [x :- s/Int, y :- s/Int, z :- s/Int]
      :return {s/Any s/Any}
      :summary "Query some stuff"
      handle-help)

then I get the following macroexpansion:

    (create
     "/help"
     :get
     (merge-parameters
      {:parameters {:query {Keyword Any, :x Int, :y Int, :z Int}},
      :responses [{200 {:schema {Any Any}, :description ""}}],
      :summary "Query some stuff"})
     nil
     (wrap-routes
      (make-route
       :get
       {:source "/help", :re #"/help", :keys [], :absolute? false}
       (fn [request__4530__auto__]
           (let-request
               [[:as +compojure-api-request+] request__4530__auto__]
               (letk
                   [[x :- Int y :- Int z :- Int]
                   (coerce!
                    {Keyword Any, :x Int, :y Int, :z Int}
                    :query-params
                    :string
                    +compojure-api-request+)]
                   (do handle-help)))))
      (compose-middleware
       [[body-coercer-middleware
       (merge {200 {:schema {Any Any}, :description ""}})]])))

There's all this junk in there I don't want, mostly the `letk` but also the `body-coercer-middleware` - really the entire `compose-middleware` section would go, if I had my way. Setting `:coercion` to nil reduces the amount of extra overhead, but calling `coerce!` still entails a noticeable amount of work, including, incredibly, a non-optional call to `clojure.walk/keywordize-keys` on my entire request!

I could write my own substitute `GET` macro, I suppose, to emit something more like this: 

    (create
     "/help"
     :get
     (merge-parameters
      {:parameters {:query {Keyword Any, :x Int, :y Int, :z Int}},
       :responses [{200 {:schema {Any Any}, :description ""}}],
       :summary "Query some stuff"})
     nil
     (make-route
      :get
      {:source "/help", :re #"/help", :keys [], :absolute? false}
      (fn [request__4530__auto__]
        handle-help)))

which is really what I want out of compojure-api: the swagger metadata, and then exactly what compojure.routes/GET would have emitted. But this seems like the kind of thing more than one person might want; perhaps there could be a way to contribute this back to compojure-api, as an option to `GET` and/or to `api`?

**Comment by ikitommi** [comment]
Thanks for sharing.

Did you try using `:swagger`? It just attaches the docs in the ring-swagger schema format. So:

```clj
(GET "/help" []
  :query-params [x :- s/Int, y :- s/Int, z :- s/Int]
  :return {s/Any s/Any}
  :summary "Query some stuff"
  (fn [_] "help"))
```

can be written as:

```clj
(GET "/help" []
  :swagger {:parameters {:query {s/Keyword s/Any, :x s/Int, :y s/Int, :z s/Int}}
            :responses {200 {:schema {s/Any s/Any} :description ""}}
            :summary "Query some stuff"}
  (fn [_] "help"))
```

macroexpanding it:

```clj
(compojure.api.routes/create
 "/help"
 :get
 (compojure.api.meta/merge-parameters
  {:swagger {:summary "Query some stuff",
             :responses {200 {:description "", :schema {schema.core/Any schema.core/Any}}},
             :parameters {:query {:y schema.core/Int,
                                  :z schema.core/Int,
                                  :x schema.core/Int,
                                  schema.core/Keyword schema.core/Any}}}})
 nil
 (compojure.core/make-route
  :get
  #clout.core.CompiledRoute{:source "/help", :re #"/help", :keys [], :absolute? false}
  (clojure.core/fn
   [request__24662__auto__]
   (compojure.core/let-request
    [[:as +compojure-api-request+] request__24662__auto__]
    (do (clojure.core/fn [user/_] "help"))))))
```

**Comment by amalloy** [comment]
Ah. I hadn't tried that, because I don't really know what all is supported for the `:swagger` spec map. It sounds like this would be a better approach than adding the `:raw true` option for `GET`, `Post`, etc. What about the `:raw true` option for `api`, though, as a way to remove the extra middlewares?

**Comment by ikitommi** [comment]
Ring-swagger format is the thing we generate from routes. `:swagger` allow one to write it as-is, so one can do all the docs just with it. There is a sample in [ring-swagger README](https://github.com/metosin/ring-swagger#more-complete-example). Also the [Swagger spec](http://swagger.io/specification/) itself is handy as a reference.

cheers.

**Comment by ikitommi** [comment]
Can this be closed?
