### ISSUE TITLE
middleware init is executed for each request

### ISSUE THREAD

**Issue by yogsototh** [metosin/compojure-api#241]
If you look at this code:

https://gist.github.com/yogsototh/7ae1911e54147e7d5ac43f1b377663f5

each request prints "INIT HANDLER".
I believe it should only be printed once.

**Comment by ikitommi** [comment]
This is inherited from Compojure, see https://github.com/weavejester/compojure/issues/148. You can use `(middleware [wrap-head] (context "/api" [] ...))` to work around this.

**Comment by yogsototh** [comment]
Thanks!

**Comment by ikitommi** [comment]
Btw, the perf tests are here: https://github.com/metosin/compojure-api/blob/master/test/compojure/api/compojure_perf_test.clj. 

For really busy apps, defining things (endpoints, middleware etc.) separately outside of the Compojure route tree and just referencing them from routing gives a bit better perf. But still, most of the processing time goes on json parsing & schema validations.

**Comment by ikitommi** [comment]
the new `1.2.0-SNAPSHOT` has a fix for this: if a `context` doesn't do any lexical bindings, it's optimized as static => the `:middleware` get created only once.
