### ISSUE TITLE
Example exception handler is incorrect

### ISSUE THREAD

**Issue by philip-doctor** [metosin/compojure-api#244]
Hey guys, sorry I usually PR things, but this is so minor I thought I'd just point it out in an issue.

https://github.com/metosin/compojure-api/blob/master/src/compojure/api/api.clj#L26

````

      (api
        {:formats [:json-kw :edn :transit-msgpack :transit-json]
         :exceptions {:compojure.api.exception/default my-logging-handler}
````

But actually that's not the proper format for the exceptions map, from the code (and personal testing) it looks like you need the following:

https://github.com/metosin/compojure-api/blob/master/src/compojure/api/middleware.clj#L152
````
   :exceptions {:handlers {::ex/request-validation ex/request-validation-handler
                           ::ex/request-parsing ex/request-parsing-handler
                           ::ex/response-validation ex/response-validation-handler
                           ::ex/default ex/safe-handler}}
````

So update the api doc example to read

````
      (api
        {:formats [:json-kw :edn :transit-msgpack :transit-json]
         :exceptions {:handlers {:compojure.api.exception/default my-logging-handler}}
````

**Comment by ikitommi** [comment]
Thanks! Fixed it.
