### ISSUE TITLE
Go async (with Ring 1.6.0 & Compojure betas)

### ISSUE THREAD

**Issue by ikitommi** [metosin/compojure-api#247]
- https://github.com/weavejester/compojure/blob/master/HISTORY.md#160-beta1-2016-07-22

* [x] wrap-exceptions
* [x] wrap-options
* [x] tests
* [x] map `manifold.deferred/deferred` (not a direct dependency)
* [x] map `core.async` channels (not a direct dependency)
* [x] Sample app

**Comment by ikitommi** [comment]
All middleware need to be lifted to support async. both in compojure-api & ring-swagger.

**Comment by miikka** [comment]
This should be documented in some way.

**Comment by ikitommi** [comment]
clue in the readme + wiki-page? and a blog when shipped.

**Comment by ikitommi** [comment]
README updated, linking to a non-existing wiki-page.

**Comment by ikitommi** [comment]
this is done? or does it still require something with `resource`s?

**Comment by miikka** [comment]
Right, `resource` does not support 3-ary handlers, although the handlers it generates have also arity 3.

**Comment by ikitommi** [comment]
Let's update deps to `1.6.0` and ship new alpha out.

**Comment by miikka** [comment]
You can now have 3-ary handlers with `resource` (see #293), but we should consider #297 before shipping out 1.2.0. I think that should be the last thing before this issue can be closed.

**Comment by miikka** [comment]
As far as I know, everything should now support async.
