### ISSUE TITLE
Swagger UI Incorrectly displays response model

### ISSUE THREAD

**Issue by gbuisson** [metosin/compojure-api#252]
I've been experiencing this since 1.1.7:
![screen shot 2016-10-11 at 16 10 27](https://cloud.githubusercontent.com/assets/1433542/19273662/96105208-8fcd-11e6-8965-b087a12158fb.png)

I also get the same issue on the example project, is it a known issue?

**Comment by ikitommi** [comment]
Hi. It was a bug in the swagger-ui 2.2.1, fixed in 2.2.2. Please try 1.1.8.

cheers,

Tommi

**Comment by gbuisson** [comment]
I confirm it's fixed on 1.1.8 ;-)
