### ISSUE TITLE
:header-params for resources not working

### ISSUE THREAD

**Issue by olivermg** [metosin/compojure-api#254]
I'm trying to specify a header parameter (via `:header-params`) for certain operations on resources. However I'm seeing the following issue (I'll be using the [compojure-api "resource" example](https://github.com/metosin/compojure-api/tree/master/examples/resources) in the following description to make things easier to reproduce).

When I alter the `:get` operation for `/pizza/` within [handler.clj](https://github.com/metosin/compojure-api/blob/master/examples/resources/src/example/handler.clj#L54), so that it reads

    (context "/pizza/" []
      (resource
        {:tags ["pizza"]
         :get {:summary "get pizzas"
               :description "get all pizzas!"
               :parameters {:header-params {:x-key s/Str}}     ;; <= added this line
               :responses {http-status/ok {:schema [Pizza]}}
               :handler (fn [_] (ok (vals @pizzas)))}
               ...

instead of

    (context "/pizza/" []
      (resource
        {:tags ["pizza"]
         :get {:summary "get pizzas"
               :description "get all pizzas!"
               :responses {http-status/ok {:schema [Pizza]}}
               :handler (fn [_] (ok (vals @pizzas)))}
               ...

, then the header-param `x-key` shows up correctly in Swagger UI, but when trying to invoke it, it spits out an error `400` along with the following response body:

    {
      "errors": "(not (map? [nil]))"
    }

When I change the additional line, so that it specifies query parameters instead of header params ( `:parameters {:query-params {:x-key s/Str}}`) then things work fine, but with query params. I'd like header params ;) .

I've tried to specify `"x-key"` instead of `:x-key` but that results in a different error.

Specifying something like `[x-key :- s/Str]` doesn't seem to be possible at that location neither.

This also happens for other operations than GET.

Is this a bug or am I doing anything wrong?

**Comment by ikitommi** [comment]
Tested that myself. It's a bug. Will fix that.

**Comment by ikitommi** [comment]
ok. found the issue. `resource` tries to read the headers from `:header-params` under the request. Should be read from `:headers`. Should be easy to fix.

**Comment by ikitommi** [comment]
https://github.com/metosin/compojure-api/blob/master/src/compojure/api/resource.clj#L14

**Comment by ikitommi** [comment]
Please try `1.1.9-SNAPSHOT`, should be fixed.

**Comment by olivermg** [comment]
Yes, it's working now. Thanks a lot for the quick fix and great work on `compojure-api` :) .

**Comment by ikitommi** [comment]
thanks :) just released `1.1.9` with just this + updated deps.
