### ISSUE TITLE
Restore weavejester/lein-ring

### ISSUE THREAD

**Issue by ccann** [metosin/compojure-api#258]
Seems like [MichaelBlume merged your PR](https://github.com/weavejester/lein-ring/commit/21a99e9cabec94cfd840b0e3c8e105f87ffd7f81) on lein-ring so can you restore weavejester/lein-ring in the compojure-api lein template? Or is there an issue blocking that?

**Comment by ikitommi** [comment]
Hi. As soon as there is a non-snapshot version of the lein-ring, we'll update.

**Comment by ikitommi** [comment]
latest template uses now `[lein-ring "0.10.0"]`.
