### ISSUE TITLE
POST with :body-params returns "errors": "(not (map? nil))"

### ISSUE THREAD

**Issue by efraimmgon** [metosin/compojure-api#262]
I am using [metosin/compojure-api "1.1.8"] and I have a simple route:

```
(POST "/send-message" req
        :body-params [a :- String]
        (ok (str "param: " a " // params: " (:params req))))
```

but I'm getting the following error and I can't figure out what might be wrong:

```
{
  "errors": "(not (map? nil))"
}
```

If I change it for a POST with :form-params it works, just as if I change it to a GET with :query-params.

**Comment by ikitommi** [comment]
Hi. For some reason, you are not receiving a body and the `:body-params` is `nil` and the Schema validation fails. You can verify this by commenting out the `:body-params` line and just printing the `:params` or `:body-params` from the request. Common causes for the nil are a) wrong `content-type` header and b) some external broken middleware. Something that is not causing the body to be parsed into `:body-params`.

hope this helps.

**Comment by ikitommi** [comment]
See #226
