### ISSUE TITLE
Wiki refers to nonexistent function

### ISSUE THREAD

**Issue by daveliepmann** [metosin/compojure-api#278]
[Building Documented Apis](https://github.com/metosin/compojure-api/wiki/Building-Documented-Apis) wiki refers extensively to `compojure.api.swagger/validate`, which does not appear to exist in v1.2.0.

**Comment by daveliepmann** [comment]
Perhaps it should refer to `compojure.api.validator`?

**Comment by ikitommi** [comment]
Oh, that's the one. Could you please fix that? All help with the docs is appeciated.

**Comment by daveliepmann** [comment]
No problem, just wasn't sure if that was correct. I updated the wiki.
