### ISSUE TITLE
'missing-required-key' for header that is made available and sent via Swagger UI

### ISSUE THREAD

**Issue by eoliphan** [metosin/compojure-api#280]
Hi,
I have a weird problem, I have a simple API like so

```
(GET "/authenticated" []
       :header-params [Authorization :- String]
       :auth-rules authenticated?
       :current-user user
       (ok ))
```

That as expected creates an "Authorization" parameter in the Swagger UI, etc. However, when I "Try it out!" with a value filled in, I'm getting a 400 and this response body:

```
{
  "errors": {
    "Authorization": "missing-required-key"
  }
}
```

I know the value is going over as it's a JWT token, I've traced through the backend code and it's grabbing the header, decoding it, etc.

I've attached a screen shot 
<img width="980" alt="screen shot 2017-02-21 at 10 28 06 pm" src="https://cloud.githubusercontent.com/assets/1065736/23196056/38a01d3a-f885-11e6-9d3b-c7437c23a256.png">

**Comment by eoliphan** [comment]
I think I've figured this out, changing authorization to lowercase seems to have fixed it

```
(GET "/authenticated" []
       :header-params [authorization :- String]
       :auth-rules authenticated?
       :current-user user
       (ok ))
```

**Comment by Deraen** [comment]
Request header names are always lower-case: https://github.com/ring-clojure/ring/blob/master/SPEC#L98

**Comment by eoliphan** [comment]
Got it, thanks!
