### ISSUE TITLE
Support for filter content-type

### ISSUE THREAD

**Issue by duqcyxwd** [metosin/compojure-api#286]
This could be a bug or feature. 
I hope compojure-api could have the ability to select the content-type of a request. It should allow user to limit the income content-type.  Currently, compojure-api will convert any unsupported type to an empty vector, this includes a raw text or an empty body.

**Comment by ikitommi** [comment]
Hi. Not exactly sure what you would like to get support to. Restrict incoming content-types for cerrain endpoints? What is your use case for this. Thanks.

**Comment by duqcyxwd** [comment]
Here is the use case for me.  I am expecting to receive a data in JSON format, which could be an empty array, so that I can store it. A user want to do a ```PUT``` request but he forget to specify the content-type. Compojure-api will replace body with an empty JSON string {}. My handler would not able to tell that whether user sent an empty array or compojure-api created it. 


This is related to a current [BUG:Swagger throws an error when a POST body is empty](https://github.com/metosin/compojure-api/issues/226).

Base on my experience, I think compojure-api would replace the body with an empty JSON string {} in following cases:
1. Unsupported content-type, such as text, html, xml
2. When content-type is not given
3. Body is nil.

I believe all the cases above should return 400 Bad request.

**Comment by ikitommi** [comment]
this should be fixed now. Please reopen if relevant.
