### ISSUE TITLE
Logging weirdness

### ISSUE THREAD

**Issue by flodiebold** [metosin/compojure-api#288]
Reproduction:
[repro_repro.zip](https://github.com/metosin/compojure-api/files/872913/repro_repro.zip)

Run the project with `lein run`, then `curl localhost:12345/health`. You'll get a nicely formatted error message in the log.

Now move the require of `[taoensso.timbre.tools.logging :as tools-logging]` in `core` below the one of the `resource` and repeat the above. You'll get a not-so-nice error message (printed without tools.logging or timbre).

I understand why this is happening, but it still seems wrong. It would be nice to have a way to force usage of clojure.tools.logging (or even directly timbre).

More importantly:
Now run `lein uberjar` and `java -jar target/uberjar/app.jar`, then again `curl localhost:12345/health`. You don't get any error message at all in the log.

If you uncomment the require of `[clojure.tools.logging]` in `resource` and try again. You'll again get a nicely formatted error message.

I don't really understand why this is happening; I assume it has something to do with the AOT compilation. Not getting any error message at all is of course not great, and having to include this require is weird...

**Comment by ikitommi** [comment]
Hi. and thanks. Could you try the `1.2.0-20170327.183238-14`.

**Comment by flodiebold** [comment]
Hi, that seems to fix both problems! Thanks for the fast fix! :)

**Comment by ikitommi** [comment]
np :)
