### ISSUE TITLE
Allow unknown schema parameters

### ISSUE THREAD

**Issue by dryewo** [metosin/compojure-api#29]
Hello metosin!

Is it possible to create schema that would not give error on unknown parameters?
For example:

```
(s/defschema Total {:total Long})
```

I want to use this schema and I also want it to accept all other parameters without validation and coercing, like:

```
{"total": 42, "foo": "bar", "nonono": 1}
```

**Comment by psalaberria002** [comment]
Hi guys,

I am having a similar issue.

I would like to have a strict request coercion and validation (extra keys not allowed), and a less strict response validation (extra keys allowed).

Do you know if this is already implemented?

Making db schema changes in a multi instance app, together with the extrict validations is a pain.

Thank you.

**Comment by ikitommi** [comment]
https://github.com/plumatic/schema/issues/120#issuecomment-336739247. Not sure how easy it's to use this from compojure-api. If this is still wanted, please open a new issue? (currently, only `matcher`s are easy to configure, this is done for the Schema/Coercer...
