### ISSUE TITLE
Mixing synchronous and asynchronous handlers in `resource`

### ISSUE THREAD

**Issue by miikka** [metosin/compojure-api#297]
@kalekale did the initial work in #293. Since it'd be nice to be able to mix and match 1-arity and 3-arity handlers, @ikitommi suggests that `:handler` for `resource` is always 1-arity and we add `:async-handler` which is always 3-arity. They would be called as follows:

1. When called synchronously, we call `:handler`. If it does not exist, we call `:async-handler` with suitable callbacks.
2. When called asynchronously, we call `:async-handler`. If it does not exist, we call `:handler` synchronously and use `send*` on the return value.

This would enable both 3-arity handlers *and* simple way to use deferreds or core.async channels.

Possibly there could be a warning if an async handler gets called synchronously (case 1), because at least I would like to know if a handler is blocking when I intended it to be async

**Comment by ikitommi** [comment]
I think it would be better not to call `:async-handler` from sync chain. I did a initial version of this yesterday in the train, kinda works. Will flush. Misses the testing of the `compojure.response/send*` at lest

**Comment by miikka** [comment]
Now implemented by #298, but still needs to be documented at least in the `resource` docstring.

**Comment by ikitommi** [comment]
Also, resource with middleware with the 3-arity case should be tested.

**Comment by miikka** [comment]
Closed by #301.
