### ISSUE TITLE
Ensure that static contexts doesn't break silently existing clients

### ISSUE THREAD

**Issue by ikitommi** [metosin/compojure-api#300]
the new static context optimization has an side-effect that potentially conditional routes in the context bodys don't work.

```clj
(context "/static" []
   (if (its-noon?)
      (GET "/noon-route" [] (ok "it's noon")))
```

will break as the route is calculated only once as the "/static" route is marked as static in the alpha. for most cases, this is a good default. Still a surprise.

Options:

1) remove the optimization
2) make it configurable somehow, "enable-static-route-optimization"?
2) it's ok.

**Comment by ikitommi** [comment]
```clj
(context "/static" []
   :dynamic true
   (if (its-noon?)
      (GET "/noon-route" [] (ok "it's noon")))
```

**Comment by miikka** [comment]
#302 implements a workaround, but well, it does not *ensure that static contexts do not break silently existing clients*.

**Comment by ikitommi** [comment]
https://github.com/metosin/compojure-api/wiki/Migration-Guide-to-2.0.0#static-context-optimization is good.
