### ISSUE TITLE
Cannot access :body on :compojure.api.exception/request-validation handler

### ISSUE THREAD

**Issue by fbellomi** [metosin/compojure-api#306]
Hi,

we would like to use the request :body on the :compojure.api.exception/request-validation handler, for logging purposes (in the context of a POST).
However, in our case (we use http-kit, I'm not sure about other servers, but  I think it would be the same with jetty) the request passed to the handler has the :body set to an already consumed stream; 

Is this the correct way to use the handler from our side? Is there a workaround to access the request body?

I think that the code which calls the handler is in the position to provide a request updated with the content extracted from the stream (ie. a byte array or a stream); in general I think that whoever consumes the stream provided as :body should at that very moment update the request.

We are using version 1.1.x

Thank you in advance for any suggestion or contribution on this issue.

**Comment by ikitommi** [comment]
Would you like to get access to the original `InputStream` or is it ok to get the parsed version of it? If the stream is already consumed & parsed, the contents are found in the  `:body-params` of the request.

With #304, the error data given to the handler will contain more information (and sadly, breaking the existing exception-handlers, there will be at least a migration guide or a api-creation time assertion helper for this).

**Comment by fbellomi** [comment]
thanks for your answer,

the parsed version would be enough, but we cannot find `:body-params` in the request that the `:compojure.api.exception/request-validation` handler gets.

The request passed to the handler has the following fields (some values are omitted for brevity):

```

{:compojure.api.middleware/options { [...] }, 
 :remote-addr 0:0:0:0:0:0:0:1, 
 :params {}, :headers { [...] }, 
:async-channel #object[org.httpkit.server.AsyncChannel 0x729a459e /0:0:0:0:0:0:0:1:8080<->/0:0:0:0:0:0:0:1:52093], 
:server-port 8080, 
:content-length 53, 
:form-params {}, 
:websocket? false, 
:query-params {}, 
:content-type application/json, 
:character-encoding utf8, 
:uri /v2/defineAvailability, 
:server-name localhost, 
:query-string nil, 
:body #object[org.httpkit.BytesInputStream 0x3de321a5 BytesInputStream[len=53]], 
:scheme :http, 
:request-method :post}
```

The `:body` appears to be already consumed; the payload is a json which fails the schema validation; in general we would like to access the payload from the handler, in order to provide better log/support for the cases where the validation fails

**Comment by ikitommi** [comment]
ok, this should be easy to fix.

**Comment by ikitommi** [comment]
looks like this, comments welcome:

```clj
(let [app (GET "/" []
            :query-params [x :- String]
            (ok))]
  (try
    (app {:request-method :get, :uri "/" :query-params {:x 1}})
    (catch Exception e
      (ex-data e))))
; {:type :compojure.api.exception/request-validation,
;  :validation :schema,
;  :value {:x 1},
;  :in [:request :query-params],
;  :schema {Keyword Any, :x java.lang.String},
;  :errors {:x (not (instance? java.lang.String 1))},
;  :request {:request-method :get,
;            :uri "/",
;            :query-params {:x 1},
;            :route-params {},
;            :params {},
;            :compojure/route [:get "/"]}}
```

**Comment by fbellomi** [comment]
Thanks,
if it also works correctly for POST queries (which was my original problem), I think it solves this issue.

**Comment by ikitommi** [comment]
Should work. Here's a the README app with a missing `:name` from body-params (perceived by the JSON client, where the `:request` is removed):

```json
{
  "type": "compojure.api.exception/request-validation",
  "validation": "schema",
  "value": {
    "description": "string",
    "size": "L",
    "origin": {
      "country": "PO",
      "city": "string"
    }
  },
  "in": [
    "request",
    "body-params"
  ],
  "schema": {
    "name": "java.lang.String",
    "#schema.core.OptionalKey{:k :description}": "java.lang.String",
    "size": [
      "enum",
      "L",
      "M",
      "S"
    ],
    "origin": {
      "country": [
        "enum",
        "PO",
        "FI"
      ],
      "city": "java.lang.String"
    }
  },
  "errors": {
    "name": "missing-required-key"
  }
}
```

**Comment by fbellomi** [comment]
Thank you very much for your support.
