### ISSUE TITLE
Documentation Suggestion

### ISSUE THREAD

**Issue by ccann** [metosin/compojure-api#312]
Just a suggestion, but I've been working with this API for a while and I only just discovered the link to https://github.com/metosin/compojure-api/blob/master/src/compojure/api/meta.clj which is hugely helpful. I was always confused by the difference between e.g. `body` and `body-params` and I couldn't find an enumeration of the options.

Exposing this file better or taking the defmethod keys and putting them in a markdown table would be super helpful for new users.

**Comment by ikitommi** [comment]
Great idea. Would you like to contribute (the better docs/table) for this?

**Comment by ccann** [comment]
Yes definitely will do when I get the time hopefully soon.

**Comment by ikitommi** [comment]
looking forward to it :)

**Comment by ikitommi** [comment]
new docs on separate issue
