### ISSUE TITLE
request coercion encoding

### ISSUE THREAD

**Issue by trgoodwin** [metosin/compojure-api#316]
i seem to be seeing strange behaviour around how compojure-api 1.1.10 decides to coerce json when passing in unescaped unicode in the request body

for example- given the following handler
`(def app
     (api
         (POST "/x" []
          :body-params [x :- s/Str]
          (ok x))))`

when i curl a body with an unescaped unicode of ` – ` 
`curl http://localhost:9999/x -H "Content-Type: application/json" -d '{"x": "Here – This"}'`

it is being parsed as: `Here â€“ This`

i wouldn't expect/nor want it being treated as `â€“`.
i seem to be missing something and any help would be appreciated

**Comment by ikitommi** [comment]
Hi. There is a option in Cheshire for this: `{:escape-non-ascii true|false}`. For the upcoming 2.0.0, the content-negotiation/formatting lib has changed from ring-middleware-format to Muuntaja, so the option is passed in differently. But both use the Cheshire defaults by default.

The docs are in transition, but think this could work:

```clj
(def app
  (api
    {:format {:params-opts {:json-kw {:escape-non-ascii false}}}}
    ....))
```

hope this helps.

**Comment by trgoodwin** [comment]
thanks.

that has helped with rationalising the weaving together of the middleware/chesire/api pieces a bit better.

strangely, we dropped down to the lowest level of cheshire parsing, trying to find the root point it occurs, but the string parses as expected without the strange â€“ occuring.

only other thoughts are whether we're hitting some strange charset issue or prismatic coercing the string further in an unexpected way. 

feel free to close this issue. 
and thanks for your help

**Comment by ikitommi** [comment]
The coercion should not touch the encoding. I think it's the r-m-f, you could try to with just that. But if you are happy, I'll close this now.
