### ISSUE TITLE
Returning a UUID string causes 500 if UUID is expected

### ISSUE THREAD

**Issue by MichaelBlume** [metosin/compojure-api#319]
Not sure this should be considered a bug. With 1.x, if an endpoint returned a UUID, I could return a string in UUID format, and the endpoint would be happy. With 2.0, it appears I must return a UUID object.

**Comment by ikitommi** [comment]
Hi. This is the reason why 1.2.0 turned into 2.0.0 - it's a BREAKING change that the response coercion does not use `json-coercion` for all responses (as with 1.2.x), instead it's configurable with default to "just validate". Here is the documentation: https://github.com/metosin/compojure-api/wiki/Coercion#custom-schema-coercion.

Just updated the guide, to enable `json-coercion` for all responses, one can say:

```clj
(require '[compojure.api.coercion.schema :as schema-coercion])

(def my-coercion
  (schema-coercion/create-coercion
    (assoc-in schema-coercion/default-options [:response :default] schema-coercion/json-coercion)))

(api
  {:coercion my-coercion}
  ...}
```

Data-driven & extendable configuration (like the new coercion) mean more power to the user but is bit more verbose to configure. Do you think the new default is bad? We could re-visit the decision before getting 2.0.0 out.

**Comment by emidln** [comment]
I don't necessarily think the new default is bad, but it is such a large
breaking change that it should be called out specifically with a link to
the section in the guide to revert to the previous behavior.

**Comment by ikitommi** [comment]
Agree. For 2.0.0 final, there will be a Migration Guide: https://github.com/metosin/compojure-api/wiki/Migration-Guide-to-2.0.0, will ensure it'll end up there.

**Comment by MichaelBlume** [comment]
Yeah, I think in that case we're fine =)

**Comment by ikitommi** [comment]
Added guide for this in the migration guide: https://github.com/metosin/compojure-api/wiki/Migration-Guide-to-2.0.0#how-does-this-effect-my-routes
