### ISSUE TITLE
clojure-api: Single main clj for multiple API handlers.

### ISSUE THREAD

**Issue by srinidagda** [metosin/compojure-api#323]
The below is my app project.clj

```
(defproject clojure-my-app-api "0.1.0-SNAPSHOT"
      :description "FIXME: write description"
      :url "http://example.com/FIXME"
      :license {:name "Eclipse Public License"
                :url "http://www.eclipse.org/legal/epl-v10.html"}
      :ring {:handler clojure-my-app-api.core/app} 
      :dependencies [[org.clojure/clojure "1.8.0"]
                     [metosin/compojure-api "1.1.10"]
                     [ring/ring-core "1.4.0"]
                     [ring/ring-jetty-adapter "1.4.0"]]
      :main clojure-my-app-api.core)
```
and my app core.clj is
```
(ns clojure-my-app-api.core
  (:require [ring.adapter.jetty :as jetty])
  (:require [compojure.api.sweet :refer :all])
  (:require [ring.util.http-response :refer :all]))

(defapi app
  (GET "/hello" []
    :query-params [name :- String]
    (ok {:message (str "Dear " name ", Hello I am here ")})))

(jetty/run-jetty app {:port 3000})
```
My doubt is, Is it mandatory to put `(jetty/run-jetty app {:port 3000})` in every clj class if we have multiple classes for handling multiple API requests.

Can you please help me out is there any single main class mechanism for multiple clj class to handle different API path.

**Comment by ikitommi** [comment]
Sorry for the slow response. You need:

* one web server per port you are listening to
* one `api` can serve from multiple clojure namespaces, example: https://github.com/metosin/c2/blob/master/src/c2/handler.clj
* there can be multiple `api`s bound in one port, `api` produces just a ring-handler, so you can have:

```clj
(routes
  (context "/admin-api" []
    (api ...))
  (context "/public-api" []
    (api ...)))
```
 
hope this helps.
