### ISSUE TITLE
Context level coercion issue

### ISSUE THREAD

**Issue by Grievoushead** [metosin/compojure-api#324]
I have 2 GET routes defined under 1 context:

```
(context "/:storeId" []
        (GET "/collections" {:as request params :params}
          :summary "Get Collections"
          :path-params [storeId :- s/Str]
          :return [Collection]
          (ok (list {:id 101 :name "My Collection"})))

        (GET "/tags" {:as request params :params}
          :summary "Get Tags"
          :path-params [storeId :- s/Str]
          :return [Tag]
          (ok (list {:id 101 :tag "My Collection"}))))
```

The schemas for each:
```
(s/defschema Collection
             {:id s/Int
              :name s/Str
              })

(s/defschema Tag
  {:id s/Int
   :tag s/Str
   })
```

The problem is that when I am doing request to 1st endpoint it works good, but when I do request to 2nd it returns following error:
`{"errors":[{"name":"missing-required-key","tag":"disallowed-key"}]}`

Seems like it is trying to validate return of 2nd route with schema of 1st route. Why is it happening?
In Swagger docs the schemas is correctly displayed for each routes.

**Comment by ikitommi** [comment]
related: https://github.com/metosin/compojure-api/issues/326. More on slack

**Comment by ikitommi** [comment]
Waiting for resolution for https://github.com/nginx-clojure/nginx-clojure/issues/182

**Comment by ikitommi** [comment]
Closing this now. Can be tracked on nginx-clojure side
