### ISSUE TITLE
make explicit dependency on Java 8

### ISSUE THREAD

**Issue by carocad** [metosin/compojure-api#325]
Hey guys,
We have been using your library and just found out that our CI test failed. After checking a bit we found out that you require a java class from `Java 8`: https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html

This is an easy solve in our CI but it was very confusing because we were looking like crazy in our own code for the bug. I think a simple "this project requires Java 8" would be great :)

extra info:
- [metosin/compojure-api "2.0.0-alpha5"]
- CI log: https://travis-ci.org/n7a235/service.routing/builds/255555606?utm_source=github_status&utm_medium=notification

**Comment by Deraen** [comment]
Hmm, Java 1.7 works with the stable version as Ring-swagger only uses Java 8 Time if it is available (https://github.com/metosin/ring-swagger/blob/042d2b555bdba24eab7bf63a84e26df66e88442f/src/ring/swagger/extension.clj#L13), I guess spec-tools doesn't have similar checks in place. We should probably add similar checks to spec-tools so next Compojure-api can be used with Java 1.7.

**Comment by Deraen** [comment]
Changelog in fact mention this: https://github.com/metosin/compojure-api/blob/master/CHANGELOG.md#120-alpha2-2212017

I also added mention to the readme: https://github.com/metosin/compojure-api/commit/3b1830e529ffd58ad48d6d1f2df06f49c85c86ba
