### ISSUE TITLE
ERROR compojure.api.exception - Request cannot be executed; I/O reactor status: STOPPED

### ISSUE THREAD

**Issue by mnebuerquo** [metosin/compojure-api#332]
I ran into this error while debugging a new app, and I don't know what it means. I'm not sure how to debug it yet, so I'm posting it here. If it's something that can be improved, that's awesome, but maybe someone will explain what it means and how to prevent it, and then people searching this in the future will find this issue and save themselves some difficulty.

I am trying to do some requests on `:start` with `mount.core/defstate`.

```
ERROR compojure.api.exception - Request cannot be executed; I/O reactor status: STOPPED
```

**Comment by ikitommi** [comment]
I think this is mount-related. Sorry, can't help :(
