### ISSUE TITLE
api function throws "No implementation of method: :specize* of protocol: #'clojure.spec.alpha/Specize found for class: nil "

### ISSUE THREAD

**Issue by carocad** [metosin/compojure-api#334]
For some reason that I am still not able to understand our api code suddenly stopped working. It all started with this commit https://github.com/n7a235/service.routing/pull/32/commits/f1a866bf782c86d71e56f672d64b4347f61bf8de

The error that I thought was happening (keyword not being correctly namespaced) was already solved. Yet the issue still continues. I already ran out of options of what might possible be wrong in our code so my best guess is that the issue comes from `compojure-api`. 

Unfortunately the "caused by " stacktrace message is not clear enough to pinpoint the source of the error. The best match so far is this: https://dev.clojure.org/jira/browse/CLJ-2032 but it doesnt seem to be directly related.

Below is the travis ci failing build and a link to the PR that created the changes in our api.

- https://github.com/n7a235/service.routing/pull/32
- https://travis-ci.org/n7a235/service.routing/builds/263862072?utm_source=github_status&utm_medium=notification

Extra information:
- I added aviso/pretty to ease understanding of the stacktrace since the original stacktrace was truncated and impossible to decipher (to me at least :/ ). Let me know if you want that disabled to get the original stacktrace. You can also get it form travis ci previous failing build logs, though.
- Both the `lein check` and `lein eastwood` seem to indicate that the problem is in fact in the defapi code.
- The error also happens in the REPL once we load the ns where defapi is used.

**Comment by mehdisadeghi** [comment]
OK, we found the problem. There was a typo in our code referring to a non-existent spec. However, compojure-api can do a better job at reporting and simply inform the user that such a spec does not exist.

**Comment by mehdisadeghi** [comment]
I would happily submit a PR if I knew where the fix should go, probably [`api/sweet/GET`](https://github.com/metosin/compojure-api/blob/29a67cb05a7996505919c8b4ff20e4566240bc40/src/compojure/api/core.clj#L61) or [`api/meta/restructure`](https://github.com/metosin/compojure-api/blob/29a67cb05a7996505919c8b4ff20e4566240bc40/src/compojure/api/meta.clj#L589) or [`api/common/extract-parameters`](https://github.com/metosin/compojure-api/blob/29a67cb05a7996505919c8b4ff20e4566240bc40/src/compojure/api/common.clj#L8)?

**Comment by mgrbyte** [comment]
It's always a programming error that's the cause, but not always obvious how to track it down (no line number in exception for example); requires scanning all specs you've defined and eyeballing them to locate the mistake. 
Am not sure this is an issue with compojure-api or a more general one, but it would be _nice_ to have a better experience here (for beginners especially).

**Comment by carocad** [comment]
@mgrbyte I dont think this is the case. True, it is usually a programming error but Clojure already reports if you are trying to use a Spec that is not defined. If it is like that, then why does compojure-api overlooks that check?

Try running this in your REPL `(s/valid? :spec/routes "hello")` and you will see that Clojure correctly tells you that there is an error. Compojure-api on the other hand, does not.

As @mehdisadeghi we would be more than happy to help with this since this is not only a beginner issue; typos happen all the time and precisely because of their nature it is very difficult to identify them

**Comment by ikitommi** [comment]
Agree that error messages should be so much better. If one references a spec that doesn't exist, I think it fails here: https://github.com/metosin/compojure-api/blob/master/src/compojure/api/coercion/spec.clj#L35-L65. PR would be welcome.

The `Coercion` protocol will most likely change a bit in the next version: more functional and faster, but should not effect how this could be fixed.

**Comment by ikitommi** [comment]
Oh, that got auto-resolved by the PR. Could you try with `[metosin/spec-tols "0.3.3-20170831.122129"]` to see if this is really fixed.

**Comment by carocad** [comment]
@ikitommi I can confirm that the latest version `[metosin/spec-tools "0.3.3-SNAPSHOT"]` sucessfully throws an error on `defapi` if an unknown spec keyword is used.

**Comment by ikitommi** [comment]
Great! Released `[metosin/spec-tools "0.3.3"]` with the fix (and with updated deps).

**Comment by mehdisadeghi** [comment]
@carocad thanks for the quick fix and @ikitommi thanks for the quick release!

**Comment by mgrbyte** [comment]
Great work @carocad & @ikitommi, thanks!
