### ISSUE TITLE
docstring metadata is not resolved correctly

### ISSUE THREAD

**Issue by carocad** [metosin/compojure-api#335]
I am not sure if this is a compojure-api issue or a Cursive-IDE one. But the docstrings metadata of several functions and macros is not being properly loaded. See image below

![captura de pantalla de 2017-08-12 18-56-51](https://user-images.githubusercontent.com/10408729/29242596-495221fe-7f90-11e7-94c9-e2427ffadbf0.png)

By checking the source code I know that you are evaluating some functions to associate the result as docstrings. Nevertheless I wonder if you forgot to make that evaluate in compile time with the inverted thick ` or if this is a Cursive error (sorry but I am not very fluent in macro/metadata evaluation)

**Comment by ikitommi** [comment]
Cursive doesn't evaluate the code, so the links are not shown. I'll ping Colin is there something he can do for this. If not, we could inline the docs...
