### ISSUE TITLE
yml dependency not found after switch to 2.0.0-alpha7

### ISSUE THREAD

**Issue by panewman** [metosin/compojure-api#337]
After switching from 2.0.0-alpha5 to 2.0.0-alpha7, my project will not compile anymore, because the clj-yml dependency is missing.
As I understand the last changelog entry, you would be required to actively do something to enable yml. That seems not the case.
I don't have any direct reference to yml in my project and I expected 2.0.0-alpha7 to work with the default options. Somehow the namespace muuntaja.format.yaml seems to be still referenced by default.

**Comment by ikitommi** [comment]
Hi.

Tested with:

```
lein new compojure-api yml-test
cd yml-test
;; update project.clj to contain [metosin/compojure-api "2.0.0-alpha7"]
lein ring server
```
seems to work as expected, and the swagger-ui doesn't show the yml or msgpack formats. You could try `lein clean`, if it doesn't help, could you provide a minimal failing example.

**Comment by panewman** [comment]
Thanks. Looks like __lein clean__ was the way to go.
