### ISSUE TITLE
Swagger stackoverflow with recursive specs

### ISSUE THREAD

**Issue by ggeoffrey** [metosin/compojure-api#339]
When I set the coercion to `:spec` and use a recursive spec like :
```
(s/def ::user nil?) ;; will be redefined below
(s/def ::name string)
(s/def ::parent (s/nilable ::user))
(s/def ::user (s/keys :req-un [::name ::parent]))
```
Swagger fail with this error:
```
{"type":"unknown-exception","class":"java.lang.StackOverflowError"}
```

It seems that the clojure.spec -> swagger conversion keep walking the recursive spec until the stack blows up.

**Comment by ikitommi** [comment]
That's not good. Copied the issue into spec-tools, where it needs to be resolved.

**Comment by ikitommi** [comment]
quick fixed in latest aplhas.
