### ISSUE TITLE
unable to specify a response spec with `s/or`

### ISSUE THREAD

**Issue by bmabey** [metosin/compojure-api#344]
This may be user error but I am unable to specify a return spec that is defined with `s/or`. Here is a gist illustrating the problem:
https://gist.github.com/bmabey/ea68b00e48f914ad3a0d4aa31c01e196

**Comment by ikitommi** [comment]
Hi. What versions of ilbs (c-api, spec-tools) are you using? I get:

```clj
(-> {:request-method :post
     :uri "/cheese"
     :headers {"content-type" "application/json"}
     :body "{\"something\": \"good\"}"}
    testapp
    :body
    slurp)
; "{\"cheese\":\"cheddar\"}"
```

**Comment by ikitommi** [comment]
Please reopen if this pops up. Should be fixed.
