### ISSUE TITLE
Lazy sequences in routing table cause strange endresultss

### ISSUE THREAD

**Issue by ikitommi** [metosin/compojure-api#348]
## Library Version(s)

`2.0.0-alpha10`

## Problem

Currently, to mount sequential routes, one needs to wrap them into `(apply routes my-routes)`. Would be nice to avoid this and support sequential routes with both `routes` and `context`. Something like:

```clj
(context "/api" []
  (for [path ["/ping" "/pong"]]
    (GET path [] (ok {:path path}))))
```
Currently, that fails with:

```clj
CompilerException java.lang.ClassCastException: clojure.lang.LazySeq cannot be cast to clojure.lang.IFn
```

**Comment by miikka** [comment]
@ikitommi, should you have actually filled the issue text?

**Comment by ikitommi** [comment]
will do.

**Comment by ikitommi** [comment]
did.
