### ISSUE TITLE
Inconsistent error response shapes

### ISSUE THREAD

**Issue by JayAndCatchFire** [metosin/compojure-api#350]
## Library Version(s)
1.1.11 (I haven't checked any of the 2.0.0 alphas.)

## Problem
The shape of the data in the responses for schema mismatches and parsing errors are inconsistent.

### Schema Mismatch Error
```json
{
  "errors": {
    "y": "(not (instance? java.lang.Long 5.4))"
  }
}
```

### Parsing Error
```json
{
  "type": "json-parse-exception",
  "message": "Unexpected end-of-input: expected close marker for Object (start marker at [Source: (StringReader); line: 1, column: 1])\n at [Source: (StringReader); line: 4, column: 24]"
}
```

(Also, EDN, Transit+JSON, and Transit+MsgPack parsing errors are significantly different. That's captured in https://github.com/metosin/compojure-api/issues/351 and https://github.com/metosin/compojure-api/issues/352.)

**Comment by ikitommi** [comment]
hi. With 2.0.0, the coercion errors produce much more info and the `ring-middleware-format` has been replaced with Muuntaja. Could you retest with latest 2.0.0 alpha and report if this still stands? 2.0.0 should be out soon.

**Comment by JayAndCatchFire** [comment]
I discovered this while working with compojure-api for my job.  I will get around to testing this with 2.0.0, but it may not be until next week or so.

**Comment by JayAndCatchFire** [comment]
This is fixed in the alpha.
