### ISSUE TITLE
500 on parsing failures of EDN and Transit+JSON

### ISSUE THREAD

**Issue by JayAndCatchFire** [metosin/compojure-api#351]
## Library Version(s)
1.1.11 (I haven't checked on any 2.0.0 alphas.)

## Problem
On JSON and YAML parsing errors, `compojure-api` returns code **400** with a body of the following schema:
```json
{
  "type": "string",
  "message": "string"
}
```

However, if there's a parsing error of edn or transit+json, it returns code **500**.

### Bad EDN Response
```json
{
  "type": "unknown-exception",
  "class": "clojure.lang.ExceptionInfo"
}
```

### Bad Transit+JSON Response
```
{
  "type": "unknown-exception",
  "class": "java.lang.RuntimeException"
}
```

**Comment by ikitommi** [comment]
`ring-middleware-format` has been replaced with Muuntaja in the new 2.*. Could you retest with latest 2.0.0 alpha and report if this still stands? 2.0.0 should be out soon.

**Comment by JayAndCatchFire** [comment]
I discovered this while working with compojure-api for my job.  I will get around to testing this with 2.0.0, but it may not be until next week or so.

**Comment by JayAndCatchFire** [comment]
This is fixed in the alpha.
