### ISSUE TITLE
Inconsistent Transit+MsgPack parsing error shape

### ISSUE THREAD

**Issue by JayAndCatchFire** [metosin/compojure-api#352]
## Library Version(s)
1.1.11 (I haven't checked on any 2.0.0 alphas.)

## Problem
On JSON and YAML parsing errors, `compojure-api` returns a body of the following schema:
```json
{
  "type": "string",
  "message": "string"
}
```

However, on a transit+msgpack parsing error, it returns a body like this:
```json
{
  "errors": "(not (map? 123))"
}
```

The shape doesn't match the other parsing errors (nor the shape of schema mismatches, see https://github.com/metosin/compojure-api/issues/350) and the error is less clear about why the request failed.

**Comment by ikitommi** [comment]
Same applies here: 
> `ring-middleware-format` has been replaced with Muuntaja in the new 2.*. Could you retest with latest 2.0.0 alpha and report if this still stands? 2.0.0 should be out soon.

**Comment by JayAndCatchFire** [comment]
I discovered this while working with compojure-api for my job.  I will get around to testing this with 2.0.0, but it may not be until next week or so.

**Comment by JayAndCatchFire** [comment]
This is fixed in the alpha.
