### ISSUE TITLE
Issue with s/and on map and predicate

### ISSUE THREAD

**Issue by safoxall** [metosin/compojure-api#353]
## Library Version(s)

Using https://github.com/metosin/c2

[org.clojure/clojure "1.9.0-alpha17"]
[metosin/compojure-api "2.0.0-alpha6"]
[metosin/spec-tools "0.3.2"]

## Problem

When defining a spec using s/and on a map and a predicate, conforms fine with spec-tools.core, but won't conform on compojure-api.

I caveat this issue by stating am newbie and am probably missing something obvious :-)

Example:

```
(:require [compojure.api.sweet :refer [context GET POST resource]]
            [ring.util.http-response :refer [ok]]
            [clojure.spec.alpha :as s]
            [spec-tools.core :as st]
            [spec-tools.spec :as spec]

(s/def ::x spec/boolean?)
(s/def ::y spec/boolean?)

(s/def ::choice  (s/and (s/keys :req-un [::foo ::bar])
                        #(not (= (:foo %) (:bar %)))))

(st/conform ::choice {:foo true, :bar false})
; => {:foo true, :bar false}

(def routes
  (context "/spec" []
    :tags ["spec"]
    :coercion :spec

    (POST "/test" []
      :summary "Return spec"
      :body        [x ::choice]
      (ok  x)))))

```
Swagger response is:
{
  "spec": "(spec-tools.core/spec {:spec (clojure.spec.alpha/and (clojure.spec.alpha/keys :req-un [:c2.spec/foo :c2.spec/bar]) (clojure.core/fn [%] (clojure.core/not (clojure.core/= (:foo %) (:bar %))))), :type :map})",
  "problems": [
    {
      "path": [],
      "pred": [
        "clojure.spec.alpha/and",
        [
          "clojure.spec.alpha/keys",
          "req-un",
          [
            "c2.spec/foo",
            "c2.spec/bar"
          ]
        ],
        [
          "clojure.core/fn",
          [
            "%"
          ],
          [
            "clojure.core/not",
            [
              "clojure.core/=",
              [
                "foo",
                "%"
              ],
              [
                "bar",
                "%"
              ]
            ]
          ]
        ]
      ],
      "val": {
        "foo": false,
        "bar": true
      },
      "via": [
        "c2.spec/choice"
      ],
      "in": []
    }
  ],
  "type": "compojure.api.exception/request-validation",
  "coercion": "spec",
  "value": {
    "foo": false,
    "bar": true
  },
  "in": [
    "request",
    "body-params"
  ]
}

**Comment by ikitommi** [comment]
Hi. This should be fixed in newer versions, just updated the C2 example to latest versions. See:

* https://github.com/metosin/compojure-api/issues/336
* https://github.com/metosin/spec-tools/blob/master/CHANGELOG.md
* https://github.com/metosin/compojure-api/blob/master/CHANGELOG.md

**Comment by safoxall** [comment]
That’s great thank you!

**Comment by ikitommi** [comment]
np
