### ISSUE TITLE
A new 1.x release

### ISSUE THREAD

**Issue by joelittlejohn** [metosin/compojure-api#362]
Hi. Is there any appetite for publishing another 1.x release, with some fixes cherry picked?

It sounds silly but I'd love to see #261 in the stable version of 1.x. I expect others have things that they'd like to see released in 1.x, since it looks like migrating to 2.x will be a non-trivial task.

Is this something you're interested in/open to? Is it worth trying to gather a list of changes that are easy to cherry-pick or could be important fixes for a final 1.x release?

**Comment by ikitommi** [comment]
That would be great. Floor is yours :)

**Comment by Deraen** [comment]
1.1.12 is released with three backported fixed. If you know other potential fixes, please create new issue(s).
