### ISSUE TITLE
What is the purpose of vector in handler definition?

### ISSUE THREAD

**Issue by Atsman** [metosin/compojure-api#363]
Hello,

```clojure
(GET "/ping" [] ; <-- What is the purpose of that vector? 
  {:summary "Ping request handler"
   :return (st/spec spec/string?)}
  (r/ok "pong"))
```

I was trying to find something in examples, but query params and body in post requests do not use it. So it seems that it is kind of "vestigial organ" for me. And if so, i don't want to write that empty vector again and again.

**Comment by ikitommi** [comment]
Hi. Compojure-api uses [Compojure](https://github.com/weavejester/compojure) under the hoods. Here's about the it's destructuring syntax: https://github.com/weavejester/compojure/wiki/Destructuring-Syntax

One use case is to capture the whole request, e.g.

```clj
(GET "/ping" request
   (printn request)
   (ok {:ping "pong"}))
```
