### ISSUE TITLE
Can I have endpoint specific Muuntaja config

### ISSUE THREAD

**Issue by danieldroit** [metosin/compojure-api#369]
## Can I have endpoint specific Muuntaja config
I'd like one of my POST endpoints to return raw string regardless of the "Content-Type' request header.
How can I do achieve this, please?

**Comment by ikitommi** [comment]
For responses: setting the content-type in an endpoint manually overrides all Muuntaja confs. e.g.

```clj
(-> (ok "string") (content-type "text/plain"))
```

should do it. For requests, there is no easy way to do it: one needs to unmount the Muuntaja from root (I believe `nil` config does it), and mount it back to only certain routes.

**Comment by ikitommi** [comment]
Did this help? can this be closed?

**Comment by danieldroit** [comment]
I have managed to achieve what I needed with:
```clj
     ; for requests on "/api/query" path it prevents Muuntaja from decoding the body
     :formats    (-> m/default-options
                     (assoc-in [:http :encode-response-body?] (constantly true))
                     (assoc-in [:http :decode-request-body?] (fn [req]
                                                               (not= "/api/query" (:uri req)))))

```
