### ISSUE TITLE
Nested Destructuring is broken

### ISSUE THREAD

**Issue by nickmbailey** [metosin/compojure-api#370]
## Library Version(s)

Discovered on 1.1.11, haven't checked any other versions yet.

## Problem

When destructuring a request object, you can only destructure the keys at the top level. Whereas in compojure any level of desctructuring is supported. The problem is fairly easy to see from the repl:

```
dev=> (require '[compojure.core :refer [GET]])
nil
dev=> (require '[compojure.api.sweet :refer [context]])
nil
dev=> (GET "/" {:keys [identity]}
 #_=>   (println identity))
#<Fn@2747f665 compojure.core/wrap_route_matches[fn]>

dev=> (GET "/" {{{:keys [user-id]} :user} :identity}
 #_=>   (println user-id))
#<Fn@11623d80 compojure.core/wrap_route_matches[fn]>

dev=> (context "" {:keys [identity]}
 #_=>   (println identity))
#function[clojure.core/identity]
#compojure.api.routes.Route
{:childs [nil]
 :handler #<Fn@3e251ea0 compojure.core/make_context[handler]>
 :info {}
 :method nil
 :path ""}

dev=> (context "" {{{:keys [user-id]} :user} :identity}
 #_=>   (println user-id))

             java.lang.RuntimeException: Unable to resolve symbol: user-id in this context
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: user-id in this context, compiling:(/private/var/folders/47/631bq0cs75q8gk7jf0r8c30h0000gn/T/form-init2896469317029772128.clj:2:3)
```

**Comment by ikitommi** [comment]
PR would be most welcome!

**Comment by nickmbailey** [comment]
Actually I was wrong here. It isn't that nested destructuring is broken, its that key destructuring is broken in general. the first example only works because 'identity' is a clojure built in function so it can resolve that. Using something like 'foo' instead of 'identity' gives the compilation error again.

**Comment by nickmbailey** [comment]
Looks like this commit fixed it in master/2.0

https://github.com/metosin/compojure-api/commit/9cdea51ecf54666980c21fa955c085c791cab5c8

Any interest in backporting to a 1.1.12? Or should I just close this ticket.

**Comment by Deraen** [comment]
Backported to 1.1.12 and released.

**Comment by nickmbailey** [comment]
Thanks!
