### ISSUE TITLE
coercion error is not caught when using channels

### ISSUE THREAD

**Issue by flodiebold** [metosin/compojure-api#371]
## Library Version(s)
2.0.0-alpha18

## Problem
When returning a channel from a resource, if the response does not match the schema, the `wrap-coerce-response` middleware throws an exception. This exception is not caught by either the middleware itself or the `Sendable` implementation for channels, so the request just times out.

I think the `Sendable` implementation for channels should just have a blanket `try` in the go block, to prevent any exceptions from causing this problem. Of course, the `wrap-coerce-response` middleware could also catch that specific exception (there's even a TODO there).

**Comment by bsteuber** [comment]
This should fix it: https://github.com/metosin/compojure-api/pull/372

**Comment by ikitommi** [comment]
Thanks for the report & the fix, should be fixed in `2.0.0-alpha19`
