### ISSUE TITLE
Default response status should be 400 for request-validation-error

### ISSUE THREAD

**Issue by mgrbyte** [metosin/compojure-api#373]
## Library Version(s)
`[metosin/compojure-api "2.0.0-alpha19"]`

## Problem
When the endpoint is a resource and spec coercion is in play,
request validation does not seem to happen and a HTTP 500 error response is returned (instead of 400).

Currently the tests state (for `:query-params`) that a 400 is returned for a regular route,
but 500 returned for a resource. 
The [later][1]  I _think_ that's an oversight?
I've started a [fork][2] which to work on a patch, but still looking at where this could be caused.

[1]: https://github.com/metosin/compojure-api/blob/master/test19/compojure/api/coercion/spec_coercion_test.clj#L296
[2]: /mgrbyte/compojure-api?branch=master

**Comment by ikitommi** [comment]
Hmm.. the tests seem to indicate that 400 is returned for request-coercion and 500 for response and the tests are run successfully. So, I can't reproduce the error. Do you have a failing test available?

**Comment by mgrbyte** [comment]
Have a test failing on my [fork[[1] if that's good?

[1]: https://github.com/mgrbyte/compojure-api?branch=master

**Comment by ikitommi** [comment]
I checked the fork. I still think it works as expected. given the specs and the route:

```clj
(s/def ::x spec/int?)
(s/def ::y spec/int?)
(s/def ::xy (s/keys :req-un [::x ::y]))
(s/def ::total spec/pos-int?)

(context "/resource" []
  (resource
    {:get {:parameters {:query-params ::xy}
           :responses {200 {:schema (s/keys :req-un [::total])}}
           :handler (fn [{{:keys [x y]} :query-params}]
                      (ok {:total (+ x y)}))}
     :post {:parameters {:body-params {:x int? (ds/opt :y) int?}}
            :responses {200 {:schema (s/keys :req-un [::total])}}
            :handler (fn [{{:keys [x y]} :body-params}]
                       (ok {:total (+ x (or y 0))}))}
     :put {:parameters {:body-params ::xy}
           :handler (fn [{body-params :body-params}]
                      (ok body-params))}}))
```

the test:

```clj
(fact "parameters as specs"
  (let [[status body] (get* app "/resource" {:x 1, :y 2})]
    status => 200
    body => {:total 3})
  (let [[status body] (get* app "/resource" {:x -1, :y -3})]
    status => 500
    body => (contains {:coercion "spec"
                       :in ["response" "body"]})))
```

work as expected: the inputs are ok (of type `int?`), but the response is not (should be `pos-int?`), thus the 500 error => server's fault.

adding a failing input-parameter case:

```clj
(fact "parameters as specs"
  (let [[status body] (get* app "/resource" {:x 1, :y 2})]
    status => 200
    body => {:total 3})
  (let [[status body] (get* app "/resource" {:x "a", :y 2})]
    status => 400
    body => (contains {:coercion "spec"
                       :in ["request" "query-params"]}))
  (let [[status body] (get* app "/resource" {:x -1, :y -3})]
    status => 500
    body => (contains {:coercion "spec"
                       :in ["response" "body"]})))
```

**Comment by mgrbyte** [comment]
Looks like I was mistaken here.
I will try to replicate the error I have encountered with a new test case;
it involved an empty string I believe, and a custom s/and spec.

Closing this for now, will re-open if I manage to reproduce.
Thank you for looking.
