### ISSUE TITLE
body as string

### ISSUE THREAD

**Issue by Lokeh** [metosin/compojure-api#380]
## Library Version(s)
[metosin/compojure-api "2.0.0-alpha19"]

## Problem

I would like to be able to access the body of a POST/PUT etc. as a string. However, I am not able to get at the raw body of the request.

There doesn't appear to be any destructuring keyword for this, and I can't read the InputStream from the request because something in the lifecycle of the compojure-api.sweet exhausts it.

Any suggestions?

**Comment by pablobcb** [comment]
encode the request body in a json string again? (via cheshire or whatever)

**Comment by Lokeh** [comment]
The body _might_ not be a JSON content-type. It could be text/plain, text/html, etc. AFAICT it still exhausts the InputStream.

For now, I have a middleware that runs before compojure-api that reads the body, puts it in a separate field on the map, and then re-creates the body. I would prefer to have more control over what compojure-api does so that this isn't necessary.

**Comment by ikitommi** [comment]
Compojure-api should only read request that have a content-type that maps the Muuntaja config. Defaults are [here](https://github.com/metosin/muuntaja#default-options). So, it should not consume body of an `text/html` request.

The body is an `InputStream` and can only be consumed once. If you need to read the original String, you need to do it before the `api` runs the default middleware stack (e.g. custom middleware), including Muuntaja body parsers. Or you could disable the Muuntaja via `api` options and re-mount it only to certain routes.

Sorry, there is no easy way to do this.

**Comment by ikitommi** [comment]
Closing this now, please reopen if there is something we can do.

**Comment by davidperrenoud** [comment]
For reference, if someone just want to read some plain text with `Content-Type: text/plain` it can be done like this:
```clojure
(POST "/endpoint" {body :body}
  :consumes ["text/plain"]

  ; Send the request body back
  (ok body))
```

Of course as said above, this won't work if the `Content-Type` header is missing.
