### ISSUE TITLE
throw error on invalid url path

### ISSUE THREAD

**Issue by carocad** [metosin/compojure-api#386]
## Library Version(s)
[metosin/compojure-api "2.0.0-alpha20"]

## Problem

Followings the README I started to make some changes and was quite surprised when, after making a request, no answer would come from the server. After several hours debugging I found out that there was a typo in the path that neither the swagger UI nor compojure-api pointed out.

It turns out that if the path does not start with `/` it is still accepted as a valid path but once in the swagger UI, the requests just never return.

The code to reproduce this is:
```

(def app
  (api
    (GET "hello" []
      :query-params [name :- String]
      (ok {:message (str "Hello, " name)}))))
```

I think this should throw an error since it is by no means a valid path.

Hope it helps

**Comment by ikitommi** [comment]
Thanks for reporting.

Compojure-api uses Compojure directly, so this should be fixerd [there](https://github.com/weavejester/compojure).
