### ISSUE TITLE
Request params JSON array support

### ISSUE THREAD

**Issue by gbuisson** [metosin/compojure-api#39]
Sorry if this has already been asked,

i can't figure out how to deal with query params in this form:
...&myParam=["x","y","z"]&...

is it possible? and if so how ?

**Comment by Deraen** [comment]
2.0 spec supports multiple predefined formats: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#user-content-fixed-fields-7 (collectionFormat)

**Comment by polymeris** [comment]
I have a somewhat related issue (maybe I should open a separate ticket), the code listed above:

``` clojure
(GET* "/foo" []
  :query-params [foo :- [String]]
  (ok foo))
```

has Swagger-UI generate the query `?foo=a,b,c`, while apparently compojure-api expects `?foo=a&foo=b&foo=c`.

I can work with either format. Is it possible to get Swagger-UI to work with one of them?

**Comment by dzhus** [comment]
On a side note, is it possible to contstrain request body to use vector schema (as in `[s/Int]`). Currently compojure-api seems to silently ignore `:body [body [s/Int]]`, although it works with `:body [body {:items [s/Int]}]`. Are top-level arrays prohibited in request bodies?

**Comment by ikitommi** [comment]
I believe this works now.

**Comment by ikitommi** [comment]
please reopen this if this is still valid

**Comment by gbuisson** [comment]
Yes it's okay you can close it
