### ISSUE TITLE
Support for LINK and UNLINK methods

### ISSUE THREAD

**Issue by jacekk** [metosin/compojure-api#405]
I created this issue to propose adding support for `LINK` and `UNLINK` methods into this library. 

AFAIUNderstand, the following piece of RFC is a draft --> https://tools.ietf.org/id/draft-snell-link-method-01.html but I find it quite *legit* to use these methods for any referencing requests in one API I am creating. Currently, I've used `POST` and `DELETE` as the library does not support LINK/UNLINK, but was wondering if anyone else has the same concerns :)

**Comment by ikitommi** [comment]
Compojure-api uses Compojure for defining the methods. If/when Compojure supports these, we should update Compojure-api too. Cheers.
