### ISSUE TITLE
Inst getting truncated 

### ISSUE THREAD

**Issue by willspecht** [metosin/compojure-api#408]
## Problem
Inst are getting truncated in response. 
Should be returning 
`{:some-field 1970-01-01T00:06:49.123Z}`
But instead get 
`{:some-field 1970-01-01T00:06:49Z}`

This is causing tests to fail since I'm generating the response with spec and it doesn't match the response mocked from the route. I tried turning off coercion for the response but the truncating is still happening. Any way I can prevent this truncation from happening? 

The example response in swagger looks correct as well but the actual response is truncated.

**Comment by danielcompton** [comment]
Can you give some more information about the content type of the response?

**Comment by danielcompton** [comment]
Can you print out the full HTTP request/response? What you've provided there doesn't look like JSON?

**Comment by willspecht** [comment]
![screen shot 2019-01-24 at 3 29 56 pm](https://user-images.githubusercontent.com/17124185/51706611-026e3d00-1fed-11e9-95d2-d6f3796860b4.png)

**Comment by willspecht** [comment]
![screen shot 2019-01-24 at 3 35 25 pm](https://user-images.githubusercontent.com/17124185/51706887-c687a780-1fed-11e9-9ba3-4fa768bee209.png)

**Comment by willspecht** [comment]
Is there any additional information I can provide to help resolve this?

**Comment by miikka** [comment]
The solution is to set jsonista's `:date-format` via Muuntaja settings – by default the date format does not include milliseconds.

**Comment by laurilehmijoki** [comment]
Thanks for the tip. @miikka is there an example where a custom `:date-format` is defined in an app that uses Compojure API?

**Comment by Deraen** [comment]
Docs have example on setting Transit readers and writers, configuring Jsonista should be quite similar.

https://github.com/metosin/compojure-api/wiki/2.0.0-Content-Negotiation-(with-Muuntaja)#with-muuntaja-instance

Muuntaja format `encoder` and `decoder` properties are used to configure Jsonista `object-mapper`s.

https://metosin.github.io/jsonista/jsonista.core.html#var-object-mapper

Something like

```clj
(def muuntaja
  (m/create
    (update-in 
      muuntaja/default-options
      [:formats "application/json"] 
      merge 
      {:encoder {:date-format "..."}})))

(api
  {:formats muuntaja}
  ...)
```

**Comment by miikka** [comment]
Since this is basically a solved issue, I'll close it.
