### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by Deraen** [metosin/compojure-api#41]
README.md is too crowded and messy.

We should probably use Wiki and simplify readme.

Possible wiki pages:
- Extension points: parameter restructuring, pointer to ring-swagger doc about json-type
- Serialization, https://github.com/metosin/compojure-api/issues/184

**Comment by Deraen** [comment]
API Docs are now generated using [codeina](https://github.com/funcool/codeina). Docstrings need improvements still.

**Comment by ikitommi** [comment]
Would love to see someone write a decent wiki tutorial & docs. Any volunteers?

**Comment by Deraen** [comment]
List of frequently asked questions / frequent problems would be good first step.

**Comment by Deraen** [comment]
Listing some frequently answered questions here:

- Configuring multiple swagger-UIs and swagger-docs on one app
- AOT configuration - making shim ns to prevent AOT

**Comment by Deraen** [comment]
Sphinx could be one option for building documentation site. It used e.g. by Python. Doesn't support Clojure API docs for now, but we already have those.

http://sphinx-doc.org/
https://docs.python.org/3/
http://sphinx-doc.org/examples.html

**Comment by Deraen** [comment]
I have now moved documentation from readme to wiki.
