### ISSUE TITLE
Leiningen compojure-api template broken out of the box (CompilerException)

### ISSUE THREAD

**Issue by eigenhombre** [metosin/compojure-api#418]
## Library Version(s)
latest master

## Problem
per the docs:

    lein new compojure-api my-api
    cd my-api
    lein do clean, ring uberjar

Gives

```
clojure.lang.Compiler$CompilerException: Syntax error macroexpanding clojure.core/fn at (clojure/core/unify.clj:83:18).
#:clojure.error{:phase :macro-syntax-check, :line 83, :column 18, :source "clojure/core/unify.clj", :symbol clojure.core/fn}
(massive stacktrace elided)
```

**Comment by eigenhombre** [comment]
Update: after generating the project generated with `lein new compojure-api my-api` and updating dependencies to more recent versions, `lein ring server` and `lein uberjar` both work.  So it's probably just a matter of updating the Leiningen template.

**Comment by ikitommi** [comment]
updated the template, should work.
