### ISSUE TITLE
Clojure upgrade to 1.9

### ISSUE THREAD

**Issue by maverickuser** [metosin/compojure-api#422]
## Library Version(s)
 <dependency>
            <groupId>metosin</groupId>
            <artifactId>compojure-api</artifactId>
            <version>1.1.2</version>
        </dependency>
## Problem
We are upgrading our application to clojure 1.9 and facing the below issue

{:clojure.spec.alpha/problems [{:path [:args], :reason "Extra input", :pred (clojure.spec.alpha/cat :attr-map (clojure.spec.alpha/? clojure.core/map?) :clauses :clojure.core.specs.alpha/ns-clauses), :val ((require [schema.core :as s])), :via [:clojure.core.specs.alpha/ns-form], :in [2]}], :clojure.spec.alpha/spec #object[clojure.spec.alpha$regex_spec_impl$reify__2436 0x2fb3c930 "clojure.spec.alpha$regex_spec_impl$reify__2436@2fb3c930"], :clojure.spec.alpha/value (ring.swagger.swagger2-schema "Schemas that Ring-Swagger expects from it's clients" (require [schema.core :as s])), :clojure.spec.alpha/args (ring.swagger.swagger2-schema "Schemas that Ring-Swagger expects from it's clients" (require [schema.core :as s]))}, compiling:(ring/swagger/swagger2_schema.clj:1:1)

**Comment by ikitommi** [comment]
We'll push 2.0.0 out soon, which will fix this.
