### ISSUE TITLE
Optional query-params

### ISSUE THREAD

**Issue by tzzh** [metosin/compojure-api#425]
## Library Version(s)
1.1.11
## Problem
Is it possible to use optional query-params with the inline syntax ?
```(GET "/routes/" request
                :query-params [????]
                :middleware [wrap-route-metrics]
```
I can get it to work with resource
```
(resource
    :get {
       :parameters {:query-params {(s/optional-key :current-status) CurrentStatus}}}
```
but that then breaks the swagger interface (I believe because of some custom middleware), and that's a frequent use case so I am wondering if there is a way to do it with the inline syntax ?
This https://github.com/metosin/compojure-api/issues/154 suggests the hack of setting default values and then having a custom coercer but I was wondering if there was a better way to do it.

**Comment by tzzh** [comment]
I ended up using empty string default value and then filtering empty strings in the handler

**Comment by ikitommi** [comment]
You can do:

```clj
:query {(s/optional-key :current-status) CurrentStatus}
```

or

```clj
:query-params [{current-status :- CurrentStatus :default-current-status-value}]
```
