### ISSUE TITLE
Clj-kondo linting issue

### ISSUE THREAD

**Issue by sindhubb** [metosin/compojure-api#457]
## Library Version(s)

[metosin/compojure-api "2.0.0-alpha31"]

## Problem

I am using Calva with Clojure-lsp and have my clj-kondo settings in `.config/clj-kondo/config.edn`. It has the following config: 

```
{:linters {:unresolved-symbol {:exclude [(compojure.api.sweet/context)]}}
                           :output {:progress true}}
```
got it from: https://clojurians-log.clojureverse.org/clj-kondo/2020-01-10/1578663826.055400

Yet I see squiggly lines warning 'unresolved symbol' under args. 

![image](https://user-images.githubusercontent.com/72066862/215746003-34eb1cc7-1fbd-48d1-bbd4-dc180b31640e.png)

What setting should I have so that I don't see this linting issue?

Thanks!

**Comment by Deraen** [comment]
The mentioned config only affects `context` macro which isn't used here.

You could similarly ignore unresolved symbol errors inside `POST` and `GET` macros in this example.

Writing real Kondo analyzers for Composure-API macros is unfeasible unfortunately.

**Comment by sindhubb** [comment]
Thank you, that did it! :)

**Comment by cldwalker** [comment]
I also encountered kondo unresolved-symbol errors for compojure.api.sweet macros. A llm wrote a 100 line hook which seems to handle 9 of the macros well enough for me
