### ISSUE TITLE
`context` macro crashes when called with function calls as argument

### ISSUE THREAD

**Issue by UweHubert** [metosin/compojure-api#495]
## Library Version(s)
2.0.0-alpha33

## Problem

The evaluation of 

`(compojure.api.core/context "/path" [] (identity {}))`

results in 

```
Syntax error macroexpanding context at (xxx.clj:1:1).
Don't know how to create ISeq from: java.lang.Boolean
```

The line of code responsible for this is in 

`compojure.api.meta/restructure`

in line 1010 (https://github.com/metosin/compojure-api/blob/2.0.0-alpha33/src/compojure/api/meta.clj#L1010):

` (when (ffirst (reset-vals! warned-non-static? true))`

The call 
`(reset-vals! warned-non-static? true)` 
always returns a vector with two booleans. 

This is then badly handled by the `ffirst`.

**Comment by imrekoszo** [comment]
@UweHubert did you ever managed to solve this? Could you perhaps share details?

**Comment by Deraen** [comment]
@imrekoszo You should place other Compojure-API "routes" (`GET` etc.) inside the `context`. Compojure-API doesn't deal with function handlers in these macros, so some cases that would be valid in Compojure, aren't valid here.
