### ISSUE TITLE
If a user's project.clj doesn't have ring-swagger-ui, no UI is available.

### ISSUE THREAD

**Issue by eigenhombre** [metosin/compojure-api#60]
We found that removing `ring-swagger-ui` from a `project.clj` for a project using `compojure-api` broke the availability of the Swagger UI functionality.

Probably either `ring-swagger-ui` needs to be in _this_ project's toplevel `project.clj`, or the README needs to be updated to warn prospective users of this pitfall.  Thanks!

**Comment by bilus** [comment]
+1 Actually more than an hour.. A warning would be great.

**Comment by Deraen** [comment]
I opened #71 about a warning.

**Comment by bilus** [comment]
Thanks!
