### ISSUE TITLE
[Question] Accept parameter as well as JSON body on POST

### ISSUE THREAD

**Issue by nikos** [metosin/compojure-api#63]
Sorry, I couldn't find anything related in the README and examples: since I am currently in the transfer from homegrown handler style porting to compujore-api I am wondering how can I more elegantly allow to accept incoming POST request data to be either given via request parameters or via JSON body, in my old code base I had assignments around the lines:

```
(let [user-alias (or (:alias params) (:alias body))
```

**Comment by ikitommi** [comment]
hi,

With right middleware, the Compojure `:params` already contains both the `:query-params` and the `:body-params`, so you can just say: `(let [user-alias (:alias params)])`. Not sure what the parameter precedence is here. There is now existing restructuring handler for `:params`, but you can add it to your client project too, something like:

```clojure
(require '[compojure.api.meta :as m])
(defmethod m/restructure-param :params [_ params acc]
  (let [schema (m/fnk-schema params)]
    (update-in acc [:letks] into [params (m/src-coerce! schema :params :query)])))
```
allows you to do:

```clojure
(POST* "/alias" []
  :params [alias :- String]
  (ok alias))
```
, which reads the alias from query-, path- or body-params. Does not produce any swagger-info yet. What kind of Swagger docs are you expecting out of that? nothing? optional query-parameter & optional-body?

**Comment by ikitommi** [comment]
... meant: there is NO existing restructuring handler for `:params`.

**Comment by ikitommi** [comment]
all good? ping if still need help.
