### ISSUE TITLE
Nested Schemas with (maybe)

### ISSUE THREAD

**Issue by caryfitzhugh** [metosin/compojure-api#64]
Hi - I'm trying to do this, I believe it should work. But it gives me all sorts of errors depending on which variation I try.  Here's a sketch of what I'm trying to do.  It is a create method, with different sets of required parameters. 

```clojure
(s/defschema OptionalParam
  (s/either {:option1 String}  {:option2 String}))

(s/defschema CreateParams1 {
  :source OptOne
  :dest      String
  })

(s/defschema CreateParamsN {
  :source OptOne
  :dest      String
  :other-variables Integer
  })

(s/defschema TopLevelCreateAWidget {
   :uuid java.util.UUID,
   :params (s/either
      CreateParams1
      ;;.....
      CreateParamsN)})
```

I have seen 
```
Can't create empty: schema.core.Either clojure
```
which made me try to do something without either and used a bunch of maybes, which didn't work either.  Because I didn't want to have a bunch of empty keys required.
  
The latest is this from the :params key.
```
   "type":"class java.lang.IllegalArgumentException","message":"error converting to json schema
```

This feels like it should just "work", I should be able to group together the create messages and have an (either) in there to let you pass in any of them...   Any suggestions?

**Comment by phadej** [comment]
Have you tried: https://github.com/metosin/ring-swagger#extra-schema-elements-supported-by-ringswaggerjson-schema-dirty

**Comment by caryfitzhugh** [comment]
I thought that is what I was trying...  Phooey.

**Comment by ikitommi** [comment]
hi.

I you are just interested in making the apis work without the swagger docs, you can always make ring-swagger ignore all schema elements it can't convert to json schema, see https://github.com/metosin/ring-swagger/blob/master/README.md#missing-schema-elements. We should promote this to compojure-api somehow, at least mention this in the README.

But you got it working?

**Comment by caryfitzhugh** [comment]
nope. not yet. I had to put it down for the weekend.  I'll look at it again
today.

Frustrating when things that you think should be "simple" bog you down for
a while.   :)

Anyway, I'm going to start at the "bottom" and try to piece it all together.

I feel like one confusion was that in the REPL I could (s/validate ...) the
messages, but in the server, when I tried to run i with "lein ring .." it
failed.

**Comment by caryfitzhugh** [comment]
My morning attempt:

THis is the error:
```
{"type":"class java.lang.IllegalArgumentException","message":"error converting to json schema [:stage (either {:a java.lang.String} {:b java.lang.String})]"}
```

This is what I was trying to do:

```clojure
(s/defschema HiveProcessingStage
    {:uuid java.util.UUID,
     :hive_uuid java.util.UUID,
     :created_at java.sql.Timestamp,
     :stage (s/either {:a String} {:b String})
    })
```

As far as I can tell, that's the simplest thing that *should* work? Yet it doesn't?

**Comment by ikitommi** [comment]
hmm. That SHOULD have worked, if you have required the required the `'ring.swagger.json-schema-dirty` ns which adds the bindings to it. Tested it also myself, it doesn't :( Using named schemas in either works semi ok with `either` (swagger-ui doesn't render the fields correctly thou):

```clojure
; required to get the DIRTY either-mapping 
(require 'ring.swagger.json-schema-dirty)

(s/defschema AMap {:a String})
(s/defschema BMap {:b String})

(s/defschema HiveProcessingStage
    {:uuid java.util.UUID,
     :hive_uuid java.util.UUID,
     :created_at java.sql.Timestamp,
     :stage (s/either AMap BMap)
    })
```

The mapping is originally in the the `dirty`-ns as it's non-deterministic and by so, not supported by the Swagger Spec. See [my old question about it](https://github.com/swagger-api/swagger-spec/issues/57#issuecomment-62365407):

> Okay, in Swagger 2.0 we explicitly decided not to support this. There are various issues with supporting it ranging from how deterministic such an API is to can most common development languages support this feature easily.

ideas:

1) try to model the api without the `either`, using `optional-keys` & `maybe`s (we are doing that, not always pretty but works). List of supported elements found at https://github.com/metosin/ring-swagger#supported-schema-elements

2) try to create your own working `either`->JSON Schema mapper, example [here](https://github.com/metosin/ring-swagger/blob/master/src/ring/swagger/json_schema_dirty.clj#L8-L9)

3) don't use swagger for the apis, just the compojure-api's schema-aware handlers (`GET*`, `POST*`etc. -> they are just code generators omitting normal Compojure/RING handlers. Works with full Clojure Schema.

**Comment by caryfitzhugh** [comment]
Hey! Thanks...

Optional-key should be good enough for me.

Thanks!
Cary
