### ISSUE TITLE
Mounting middlewares example doesn't work

### ISSUE THREAD

**Issue by jsyrjala** [metosin/compojure-api#66]
See Mounting middlewares -section in README. https://github.com/metosin/compojure-api

The section seems to indicate that these fragments work identically

    (defroutes api-routes
      (middlewares [api-middleware]
         .... )

    (defapi app
       ... )
  

Actually the former fails with this exception:

      java.lang.RuntimeException: Unable to resolve symbol: +routes+ in this context

I think that the former example should be something like this:

    (ns ...
     (:require [compojure.api.routes :as routes]))

    (defroutes api-routes
      (middlewares [api-middleware]
        (routes/with-routes
           .... ))

**Comment by Deraen** [comment]
Hi,

I was unable to reproduce this. Could you check this e.g. using latest git version and the examples/thingie ns?

**Comment by ikitommi** [comment]
rewriting the internals, route collecting always from the root. Will remove the current nonsense.

**Comment by ikitommi** [comment]
fixed docs in https://github.com/metosin/compojure-api/tree/swagger2routes
