### ISSUE TITLE
File uploads

### ISSUE THREAD

**Issue by bilus** [metosin/compojure-api#74]
I cannot wrap my head about using the library to handle uploads:

```clojure
(s/defschema Upload
  {:tempfile File
   :filename String})

  (defapi api-routes
          (swagger-ui "/api" :swagger-docs "/api/api-docs")
          (swagger-docs :title "ProtON Red REST API")

(defapi api-routes
          (swagger-ui "/api" :swagger-docs "/api/api-docs")
          (swagger-docs :title "abc")
          (swaggered "jobs"
                     :description "Background jobs"
                     (context "/api/1/jobs" _
                              (POST* "/restores" {{{tempfile :tempfile filename :filename} :file params-edn :params} :params :as req} ;; TODO: Create a helper in upload.clj to match upload.cljs
                                     :form-params [file :- Upload]
                                     identity))))
```

It doesn't trigger any server-side errors but results in `Uncaught TypeError: Cannot read property 'toLowerCase' of undefined` in JS:

```
SwaggerOperationswagger.js:496 
SwaggerResource.addOperationsswagger.js:427 
SwaggerResource.addApiDeclarationswagger.js:376 
obj.on.responseswagger.js:1523 
...
```

(`type` is undefined.)

What am I doing wrong?

**Comment by Deraen** [comment]
You should wrap routes taking in multipart requests inside [ring.middleware.multipart-params/wrap-multipart-params](https://ring-clojure.github.io/ring/ring.middleware.multipart-params.html). For this you can use either `middlewares` function or `:middlewares` restructuring param. Also, there is no support for file uploads in ring-swagger yet (metosin/ring-swagger#32) nor is there support for destructuring  `:multipart-params`. `:form-params` is for urlencoded requests so that wont help with file uploads.


```clj
(s/defschema Upload
  {:tempfile s/Any
   :filename String})

(defapi api-routes
  (swagger-ui "/api" :swagger-docs "/api/api-docs")
  (swagger-docs :title "abc")
  (swaggered "jobs"
    :description "Background jobs"
    (context "/api/1/jobs" _
      (middlewares [(wrap-multipart-params)] ; Alternative 1
          (POST* "/restores" req
            :middlewares [(wrap-multipart-params)] ; Alternative 2
            (println (get-in req [:multipart-params "file"])
            identity))))
```

**Comment by bilus** [comment]
It is wrapped, sorry for not mentioning that. It actually puts it into :params which I've tried to make work using the following code:

```clojure
(defmethod compojure.api.meta/restructure-param :params [_ params acc]
  (let [schema (compojure.api.meta/strict (compojure.api.meta/fnk-schema params))]
    (-> acc
        (update-in [:parameters :parameters] conj {:type :params :model schema})
        (update-in [:letks] into [params (compojure.api.meta/src-coerce! schema :params :json)]))))
```

(obviously along with `:params` instead of `:form-params` inside `POST*`.)

It produces the same JS error. Note that I didn't anywhere near actually POSTing anything, I'm trying to get swagger-ui to work so I don't think middleware etc. has to do anything with it, does it?

**Comment by Deraen** [comment]
Try changing File schema to `s/Any`, ring-swagger doesn't know how to handle File-type.

**Comment by bilus** [comment]
I've actually tried this with:

```clojure
(s/defschema Upload
  {:tempfile s/Any
   :filename String})
```

along with `:params [file :- Upload]` and it produces the same JS error suggesting that either schemas don't work at all except in `:body` or that I'm completely confused. I'd actually bet on the latter option.

**Comment by Deraen** [comment]
Oh, right. `:type :params` is valid Swagger spec.
Try `(update-in [:parameters :parameters] conj {:type :body :model schema})`

**Comment by bilus** [comment]
Thanks! It looks I'm making some progress. :)

It would be fabulous to add support for file uploads, I think Swagger 2.0
does support it natively, am I right?

**Comment by bilus** [comment]
FYI one thing is that with `s/Any` it doesn't show it in Model Schema, it's just `filename`:

```json
 "file": {
    "filename": ""
  }
```

**Comment by Deraen** [comment]
File uploads are support by Swagger, that's why issue metosin/ring-swagger#32 exists.

After that is implemented we should probably add some restructuring handler to c-api to make file uploads easier.

**Comment by bilus** [comment]
Thank you!

**Comment by Deraen** [comment]
#84

**Comment by francoisroyer** [comment]
+1

**Comment by Deraen** [comment]
The latest snapshot has experimental support for this: http://metosin.github.io/compojure-api/doc/compojure.api.upload.html
It is experimental because it's probable that once this is tested and decided it works well we'll move the implementation to ring-swagger.

Please test and comment.

**Comment by Deraen** [comment]
Example here: https://github.com/metosin/compojure-api/blob/master/examples/src/examples/thingie.clj#L187-L194

You'll need to use :middlewares, :consumes and :multipart-params together, we are still thinking about how to simplify using this.

**Comment by ikitommi** [comment]
See `0.21.0` docs.
