### ISSUE TITLE
Unresolved dependencies when using `defroutes*` in a seperate file

### ISSUE THREAD

**Issue by mveytsman** [metosin/compojure-api#78]
I define my api in handler.clj
```clojure
(defapi canary-api
  {:formats [:json]}
  (swagger-ui)
  (swagger-docs
   :title "Canary API")
  (swaggered "API"
      :description "API health"
      status-routes)
  
  (swaggered "Artifacts"
      :description "Software artifacts"
      artifact-routes)

  (swaggered "Users"
      :description "Canary users"
      user-routes))
```

Then in another file, status.clj, I define the routes as such:

```clojure
(defroutes* status-routes
  (context "/v1" []
        (GET* "/status" []
          :summary "API status"
          :return (s/schema-with-name {:status String} "Status")
          (ok {:status "ok"}))))
```

I'm finding that when `status-routes` requires a namespace (for instance `ok` from `ring.util.http-response`), my project fails compilation unless I require `ok` from `ring.util.http-response` in handler.clj as well.

Any idea why this is going on?

**Comment by Deraen** [comment]
https://github.com/metosin/compojure-api#current-major-issues
#33

**Comment by mveytsman** [comment]
Ah I totally missed this, thanks.
