### ISSUE TITLE
Defroutes* namespace resolution breaks path-params letks

### ISSUE THREAD

**Issue by Deraen** [metosin/compojure-api#82]
When e.g. `:path-params` is used inside `defroutes*` the source is stored to the meta data with symbols namespace resolved. `[id :- s/Str] ; => [foobar.domain/id :- s/Str]`.

This causes problems when schema is created from the letk form, instead of `{:id s/Str}`, `{:foobar.domain/id s/Str}` is created. While this looks ok and everything works, this causes duplicates with path-parameters as the path-params schema is merged together with schema generated based on the uri (which is missing the namespaces).

A possible fix here: https://github.com/metosin/compojure-api/tree/fnk-schema-ns-hack

**Comment by francoisroyer** [comment]
+1
Just hit this too while following your commits on 0.20 :)

**Comment by Deraen** [comment]
Should be fixed with the latest snapshot (fixed in PR #85).
