### ISSUE TITLE
Collecting from a sequence of routes

### ISSUE THREAD

**Issue by francoisroyer** [metosin/compojure-api#86]
Any idea / recommendation on collecting from a seq of routes, e.g. something like:
(context* ""/api" []
   (apply routes* my-seq-of-documented-routes) 
)
?
Thanks!!

**Comment by Deraen** [comment]
What do you mean?

Limiting the route collection to only some contexts?

For now you can use `:no-doc true` metadata for your non-api routes.

**Comment by francoisroyer** [comment]
oops - cut-and-paste issue I guess - I meant something like:

(context* "/api" 
  (apply routes* [some-routes more-routes])
)

and, defined in another namespace and imported:

(defroutes* some-routes
...
)

(defroutes* more-routes
...
)

**Comment by Deraen** [comment]
```
(context* "/api" []
  some-routes more-routes)
```

should work (remember the binding form for context*)

**Comment by francoisroyer** [comment]
It does indeed in this exemple - but docs are not resolved in this case:

(context* "/api" 
 seq-of-routes
)

where seq-of-routes has been built separately (routes were collected from different namespaces in a previous step, then passed into the context* above)

**Comment by ikitommi** [comment]
hi.

the route-tree and with that, the api documentation, is collected at compile-time to avoid any run-time penalty for the actual app. There is no way to collect routes from a runtime generated paths. 

See: https://github.com/metosin/compojure-api/blob/88cd4d2200731fee8d1435540b0dba8d533a30b8/test/compojure/api/swagger_test.clj#L38-L44 & https://github.com/metosin/compojure-api/tree/88cd4d2200731fee8d1435540b0dba8d533a30b8#features-and-weird-things

If you can create the route lists at compile-time, you're all good. All macros on (top of Vanilla Compojure Macros) are expanded, see https://github.com/metosin/compojure-api/blob/88cd4d2200731fee8d1435540b0dba8d533a30b8/test/compojure/api/swagger_test.clj#L55-L59.

**Comment by ikitommi** [comment]
better link for the last thingie: https://github.com/metosin/compojure-api/blob/88cd4d2200731fee8d1435540b0dba8d533a30b8/test/compojure/api/swagger_test.clj#L46-L59

**Comment by francoisroyer** [comment]
Got it, thank you. I am using Sierra's component lib to collect api resources at run time, so I need to introduce some notion of "phase" to build the graph in two steps, pallet style.

**Comment by ikitommi** [comment]
We also use Component (should update the lein templates with decent config), but with all the routes collected by one Component, so haven't had this issue. 

We **could** make the `defroutes*` contain it's own static route tree to make it more independent and by so, more composable. Don't have the time for this now, PRs welcome!

PS. https://gist.github.com/Deraen/9d65f447593859dd07ae
