### ISSUE TITLE
Maps with arbitrary keys can't be used as schema

### ISSUE THREAD

**Issue by smee** [metosin/compojure-api#93]
This route leads to an exception at runtime. The return type is a map with arbitrary string keys, not keywords. It looks as if only maps with fixed enumerable keys (keyword, optional-key) can be used as a schema?

```clojure
(GET* "/foo" []
   :return {String String}
  (resp/ok {:foo "test"}))```

At runtime I see this exception:
```
java.lang.RuntimeException: Bad explicit key: class java.lang.String
	at schema.core$explicit_schema_key.invoke(core.clj:631)
	at ring.swagger.json_schema$properties$iter__8496__8500$fn__8501.invoke(json_schema.clj:142)
[...snip....]
	at clojure.core$into.invoke(core.clj:6596)
	at ring.swagger.json_schema$properties.invoke(json_schema.clj:139)
	at ring.swagger.swagger2$__GT_properties.invoke(swagger2.clj:36)
	at ring.swagger.swagger2$transform.invoke(swagger2.clj:63)
	at clojure.core$comp$fn__4492.invoke(core.clj:2436)
[...snip....]
	at ring.swagger.swagger2$transform_models.invoke(swagger2.clj:77)
	at ring.swagger.swagger2$extract_paths_and_definitions.invoke(swagger2.clj:151)
	at ring.swagger.swagger2$eval12508$swagger_json__12509$fn__12512.invoke(swagger2.clj:209)
	at ring.swagger.swagger2$eval12508$swagger_json__12509.invoke(swagger2.clj:194)
	at ring.swagger.swagger2$eval12508$swagger_json__12509$fn__12510.invoke(swagger2.clj:204)
	at ring.swagger.swagger2$eval12508$swagger_json__12509.invoke(swagger2.clj:194)```

**Comment by ikitommi** [comment]
hi.

Schemas should have keyword keys. You can use `Keyword` for the "any key":

```clojure
(require ´[schema.core :as s])
(GET* "/foo" []
   :return {s/Keyword s/Str}
  (resp/ok {:foo "test"}))
```

the current swagger-ui doesn't render that correctly (the generated `additionalProperties`),  but works as expected.

**Comment by ikitommi** [comment]
.... and that could blow up at compile time with a meaningful error message.

**Comment by andrew-nguyen** [comment]
@ikitommi What is the reasoning behind schemas being required to have keyword keys?  Is this a requirement of swagger in some way?

Here is an example from schema's documentation that allows for non-keyword keys:

```clojure
;; nested map from long to String to double
(s/validate {long {String double}} {1 {"2" 3.0 "4" 5.0}})
```

The use case here is that I would like to return a map of with a schema `{s/Str s/Num}` where the keys are dynamically generated based on the original request.

**Comment by ikitommi** [comment]
Swagger doesn't require it. Compojure-api uses Ring-swagger, which uses `s/explicit-schema-key` in few places, which blows with non-keyword / wrapped keys. These could be guarded so that it would allow String-keys. You can write an issue there (or better, a PR).

But: if the String-keys would be used with JSON (body) input, one also needs to change the JSON serialization (defaults to using keyword keys with maps - a app-level setting) or the JSON coercion (convert keyword-keys keys to strings - can be app-level or route-spesific).

This works already:

```clojure
(GET* "/" []
  :return {s/Keyword s/Num}
  (ok {:kikka 2.0}))
```

, which generates the following JSON Schema:

```json
{
  "type": "object",
  "additionalProperties": {
    "format": "double",
    "type": "number"
  }
}
```

... which still doesn't render anything to swagger-ui, see https://github.com/swagger-api/swagger-ui/issues/558

**Comment by ikitommi** [comment]
... and you can convert the maps keys to keywords manually with https://clojuredocs.org/clojure.walk/keywordize-keys or with a custom coercer.

**Comment by bhavikac** [comment]
i have same issue i wants to add a key like **data**  and i also wants to remove this  square brackets  can u please let me know how to do that.
"profile": [
    {
      "first_name": "string",
      "last_name": "string",
      "email": "string",
      "phone_number": "string",
      "profile_pic_url": "string"
    }
  ],
  "device": [
    {
      "id": "string",
      "os_name": "string",
      "os_version": "string"
    }

**Comment by Macroz** [comment]
I was also bitten by this. I wanted to receive a map of `{Long s/Str}` in the body. I now have a manual pass for converting the keys from `s/Keyword` to `Long`.

**Comment by ikitommi** [comment]
Oh, I think that these should have worked with the latest versions.  Could you write an new issue describing what fails with. Thanks.
