### ISSUE TITLE
Support for ordered-map in route :return or :body schemas.

### ISSUE THREAD

**Issue by psarando** [metosin/compojure-api#95]
According to the [CHANGELOG for v0.15.1](https://github.com/metosin/compojure-api/blob/master/CHANGELOG.md#0151-1982014):
> Use flatland.ordered.map/ordered-map when Schema has many properties and you want to keep the order intact

This works great for generating the Swagger docs and keeping the schema properties in order, but once a request is submitted to an endpoint that defines a `:return` schema with an `ordered-map`, an `IllegalArgumentException` is thrown:
> java.lang.IllegalArgumentException: No implementation of method: :walker of protocol: #'schema.core/Schema found for class: flatland.ordered.map.OrderedMap

For example, we have an endpoint defined like this:
```clojure
(defschema FileStat
  (ordered-map
    :id (describe UUID "The UUID of this data item")
    :path (describe NonBlankString "The IRODS paths to this data item")
    :type (describe DataTypeEnum "The data item's type")
    :date-created (describe Long "The date this data item was created")
    :date-modified (describe Long "The date this data item was last modified")
    :permission (describe PermissionEnum "The requesting user's permissions on this data item")
    :file-size (describe Long "The size in bytes of this file")
    :content-type (describe NonBlankString "The detected media type of the data contained in this file")
    :infoType (describe NonBlankString "The type of contents in this file")
    :md5 (describe NonBlankString "The md5 hash of this file's contents")))

(defroutes* data-operations
  (context* "/data" []
    :tags ["Data Operations"]
;; snip...
    (POST* "/:data-id/metadata/save" [:as {uri :uri}]
      :path-params [data-id :- DataIdPathParam]
      :query [params QueryParamsRequired]
      :body [body MetadataSaveRequest]
      :return FileStat
      :summary "..."
      :description "..."
      (do-metadata-save data-id params body))))
```
If the `FileStat` model returned from this endpoint is defined with an `ordered-map`, the `IllegalArgumentException` is thrown in the response, even when the request succeeds.

This exception is also thrown if the `MetadataSaveRequest` body schema is defined with an `ordered-map`, but the exception is thrown before our `do-metadata-save` function is called.

**Comment by ikitommi** [comment]
hi.

I managed to repeat the problem with just the `prismatic/schema`. Will push a fix soon.

**Comment by ikitommi** [comment]
updating to `[prismatic/schema "0.4.2"]` seemd to fix the problem, now with tests of it.

Could you retry with `[metosin/compojure-api "0.20.1-SNAPSHOT"]`?

**Comment by psarando** [comment]
I retried with `[metosin/compojure-api "0.20.1-SNAPSHOT"]` and saw lein download `metosin/compojure-api/0.20.1-SNAPSHOT/compojure-api-0.20.1-20150430.110214-1.jar`, `metosin/ring-swagger/0.20.2-SNAPSHOT/ring-swagger-0.20.2-20150429.184644-3.jar`, and `prismatic/schema/0.4.2/schema-0.4.2.jar` from clojars, but I'm still getting the IllegalArgumentException from my endpoint.

Does the `Schema` protocol need to be extended for the `flatland.ordered.map.OrderedMap` class?

**Comment by ikitommi** [comment]
Running the code within compojure-api source project, all is good:

````clojure
➜  compojure-api git:(master) lein repl

examples.server=> (require '[schema.core :as s])
nil
examples.server=> (require '[flatland.ordered.map :as m])
nil
examples.server=> (satisfies? s/Schema (m/ordered-map {}))
true
```

, but when using as a dependency, it fails:

```clojure
lein try metosin/compojure-api "0.20.1-SNAPSHOT"
Retrieving metosin/compojure-api/0.20.1-SNAPSHOT/compojure-api-0.20.1-20150501.070351-2.pom from clojars
Retrieving metosin/compojure-api/0.20.1-SNAPSHOT/compojure-api-0.20.1-20150501.070351-2.jar from clojars

user=> (require '[schema.core :as s])
nil
user=> (require '[flatland.ordered.map :as m])
nil
user=> (satisfies? s/Schema (m/ordered-map {}))
false
```

will investigate.

**Comment by ikitommi** [comment]
Let's keep this open. Will try a PR to Schema to extend `Schema` for `clojure.lang.IPersistentMap` instead of `clojure.lang.APersistentMap`.

**Comment by ikitommi** [comment]
The Schema PR is closed now with status: "Closing for now -- we have some changes coming that should take care of this in a more general way."

It's anyway a issue for the Schema, not compojure-api, so closing this too. Changed the CHANGELOG entry, I guess it never really worked :(

**Comment by yogsototh** [comment]
Just an update, using <https://github.com/frankiesardo/linked> I found a way to make it work:

~~~ {.clojure}
(defschema Foo 
  (linked/map :a (describe String "a descr") :b (describe Int "b descr")))
...
(defn l2h [l]
  (apply hash-map (mapcat identity l)))

(extend-protocol schema.core/Schema
  linked.map.LinkedMap
  (spec [this] (s/spec (l2h this)))
  (explain [this] (s/explain (l2h this))))
~~~

It may exists a better way. I will be happy to know.

**Comment by ikitommi** [comment]
nice! we could add that to ring-swagger as it already depends on both Linked & Schema.

**Comment by Deraen** [comment]
I would maybe prefer copying `map-spec` and `map-explain` from schema.core instead of converting linked-maps to normal maps. Unfortunately the functions are not public: https://github.com/plumatic/schema/blob/master/src/cljx/schema/core.cljx#L820-L828

I wounder if it would make sense to ask for those functions to be made public?
