### ISSUE TITLE
With compojure-api 0.20.0 ui seems to fail to form correct URIs when deployed with a URI prefix

### ISSUE THREAD

**Issue by MichaelBlume** [metosin/compojure-api#98]
I just updated my app to compojure-api 0.20.0, everything seems to work fine, but when I deploy my app as a war to a tomcat server, tomcat puts the name of my app in front of all the uris. If I try to poke one of my endpoints through the ui, the ui tries to hit the endpoint without the name of my app in front. This all seems to work out fine in 0.19.3.

**Comment by ikitommi** [comment]
ok, this is regression, don't have automated tests for running under app-servers. Root cause is probably that we are not setting the optional `:base-path`.

**Comment by ikitommi** [comment]
created a fix & tested with jetty-runner & added mocked automated tests. Could you retry with `[metosin/compojure-api "0.20.1-SNAPSHOT"]` and report if it's ok. Will cut a new release if all good.

**Comment by MichaelBlume** [comment]
Yep, exactly right, thanks =)

**Comment by ikitommi** [comment]
```clojure
[metosin/compojure-api "0.20.1"]
```

**Comment by MichaelBlume** [comment]
=)
